package com.themuffinman.app.chat.model;

public enum ChatAuditEventType {
    GROUP_CONVERSATION_CREATED,
    GROUP_CONVERSATION_RENAMED,
    GROUP_PARTICIPANTS_ADDED,
    GROUP_PARTICIPANT_ROLE_UPDATED,
    GROUP_PARTICIPANT_REMOVED,
    GROUP_PARTICIPANT_LEFT,
    GROUP_OWNERSHIP_TRANSFERRED,
    MESSAGE_REACTION_ADDED,
    MESSAGE_REACTION_REMOVED,
    ADMIN_MESSAGE_REMOVED,
    WEBSOCKET_AUTH_FAILED,
    WEBSOCKET_CONNECTED,
    WEBSOCKET_DISCONNECTED,
    WEBSOCKET_PING,
    WEBSOCKET_TYPING_UPDATED,
    WEBSOCKET_INVALID_PAYLOAD,
    RATE_LIMIT_EXCEEDED
}
