<script setup lang="ts">
import {onMounted, ref} from "vue"
import {RouterLink} from "vue-router"
import {userShellApi, type ActivityItem} from "../api/userShellApi.ts"
const items = ref<ActivityItem[]>([]); const loading = ref(true); const error = ref(""); const selectionHint = "Select a resume item, then use its allowed action."
const load = async () => { loading.value = true; error.value = ""; try { items.value = await userShellApi.getActivity() } catch { error.value = "Could not load activity." } finally { loading.value = false } }
const dismiss = async (item: ActivityItem) => { if (!item.resumeKey) return; try { await userShellApi.dismissActivityResume(item.resumeKey); items.value = items.value.filter(current => current.resumeKey !== item.resumeKey) } catch { error.value = "Could not dismiss this suggestion." } }
onMounted(() => void load())
</script>
<template><section class="activity"><header><p class="eyebrow">Account / History</p><h1>Activity</h1><p>Recent viewer-scoped updates and safe task resumes.</p><p class="activity__selection-hint">{{ selectionHint }}</p></header><p v-if="error" class="error" role="alert">{{ error }} <button type="button" @click="load">Retry</button></p><p v-if="loading">Loading.</p><p v-else-if="!items.length">No recent activity.</p><div v-else class="list"><article v-for="item in items" :key="`${item.kind}-${item.resumeKey || item.occurredAt}`"><div><small>Source · {{ item.kind }}</small><strong>{{ item.title }}</strong><span>{{ item.summary }}</span></div><div class="actions"><RouterLink v-if="item.route" :to="item.route">{{ item.resumable ? "Continue" : "Open" }}</RouterLink><button v-if="item.resumable" type="button" @click="dismiss(item)">Dismiss</button></div></article></div></section></template>
<style scoped>.activity{display:grid;gap:1rem;max-width:52rem}.eyebrow{margin:0 0 .3rem;color:var(--text-muted);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem)}header p:last-child{color:var(--text-muted)}.list{display:grid;gap:.45rem}.list article{display:flex;justify-content:space-between;gap:1rem;padding:.85rem;border:1px solid var(--border-subtle)}article div:first-child{display:grid;gap:.2rem}small,span{color:var(--text-muted);font-size:.8rem}.actions{display:flex;gap:.35rem;align-items:center}.actions a,.actions button{border:1px solid var(--border-subtle);border-radius:999px;padding:.45rem .7rem;background:transparent;color:inherit;font:inherit;text-decoration:none;cursor:pointer}.error{color:var(--danger)}@media(max-width:620px){.list article{align-items:start;flex-direction:column}}</style>
