<script setup lang="ts">
import {onMounted, ref} from "vue"
import {RouterLink} from "vue-router"
import {userShellApi, type ActivityItem} from "../api/userShellApi.ts"
import AppStatus from "../components/AppStatus.vue"
import AppButton from "../components/AppButton.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
import ActivityRail from "../components/ActivityRail.vue"
const items = ref<ActivityItem[]>([]); const loading = ref(true); const error = ref(""); const dismissingKey = ref<string | null>(null); const selectionHint = "Select a resume item, then use its allowed action."
const load = async () => { loading.value = true; error.value = ""; try { items.value = await userShellApi.getActivity() } catch { error.value = "Could not load activity." } finally { loading.value = false } }
const dismiss = async (item: ActivityItem) => { if (!item.resumeKey) return; dismissingKey.value = item.resumeKey; try { await userShellApi.dismissActivityResume(item.resumeKey); items.value = items.value.filter(current => current.resumeKey !== item.resumeKey) } catch { error.value = "Could not dismiss this suggestion." } finally { dismissingKey.value = null } }
onMounted(() => void load())
</script>
<template><section class="activity"><header><p class="eyebrow">Account / History</p><h1>Activity</h1><p>Recent viewer-scoped updates and safe task resumes.</p><p class="activity__selection-hint">{{ selectionHint }}</p></header><CollectionToolbar title="Recent activity" :count="items.length" :busy="loading" /><AppStatus v-if="error" :message="error" tone="error" retry @retry="load" /><AppStatus v-if="loading" message="Loading activity." busy /><AppStatus v-else-if="!items.length" message="No recent activity." /><div v-else class="activity__workspace"><div class="list"><SurfaceRow v-for="item in items" :key="`${item.kind}-${item.resumeKey || item.occurredAt}`" :row="{id: `${item.kind}-${item.resumeKey || item.occurredAt}`, title: item.title, description: item.summary, badge: item.kind, meta: item.resumable ? 'Resume available' : undefined, to: item.route || undefined}"><template #actions><RouterLink v-if="item.route" :to="item.route">{{ item.primaryActionLabel }}</RouterLink><AppButton v-if="item.resumable" type="button" tone="quiet" :loading="dismissingKey === item.resumeKey" @click="dismiss(item)">Dismiss</AppButton></template></SurfaceRow></div><ActivityRail :items="items" title="Recent context" empty-label="No recent context." /></div></section></template>
<style scoped>.activity{display:grid;gap:var(--space-3);max-width:none}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1{margin:0;color:var(--text);font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}header p:last-child,.activity__selection-hint{color:var(--text-muted)}.activity__workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(18rem,var(--detail-rail-width));overflow:hidden;border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.list{min-width:0;overflow:hidden}.list :deep(.surface-row:last-child){border-bottom:0}.activity__workspace :deep(.activity-rail){border-left:1px solid var(--border-subtle);background:var(--rail-canvas)}@media(max-width:980px){.activity__workspace{grid-template-columns:1fr}.activity__workspace :deep(.activity-rail){border-top:1px solid var(--border-subtle);border-left:0}}</style>
