<script setup lang="ts">
import {onMounted, ref} from "vue"
import type {BusinessAvailabilityExceptionRequestDTO, BusinessAvailabilityExceptionResponseDTO, BusinessOfferingResponseDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"

const items = ref<BusinessAvailabilityExceptionResponseDTO[]>([])
const offerings = ref<BusinessOfferingResponseDTO[]>([])
const form = ref<BusinessAvailabilityExceptionRequestDTO | null>(null)
const editingId = ref<number | null>(null)
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref("")
const feedback = ref("")
const emptyForm = (): BusinessAvailabilityExceptionRequestDTO => ({businessOfferingId: offerings.value[0]?.id ?? 0, exceptionType: "BLOCK", startAt: "", endAt: "", replacementCapacity: 1, replacementStartTimeLocal: "09:00", replacementEndTimeLocal: "17:00", reason: ""})
const formatDate = (value: string) => new Intl.DateTimeFormat("en-US", {month: "short", day: "numeric", hour: "numeric", minute: "2-digit"}).format(new Date(value))
const load = async () => { isLoading.value = true; error.value = ""; try { const [exceptionResponse, offeringResponse] = await Promise.all([userShellApi.getBusinessAvailabilityExceptions(), userShellApi.getBusinessOfferings()]); items.value = exceptionResponse.items; offerings.value = offeringResponse.items } catch { error.value = "Could not load availability exceptions." } finally { isLoading.value = false } }
const beginCreate = () => { editingId.value = null; form.value = emptyForm(); feedback.value = "" }
const beginEdit = (item: BusinessAvailabilityExceptionResponseDTO) => { editingId.value = item.id; form.value = {businessOfferingId: item.businessOfferingId, exceptionType: item.exceptionType, startAt: item.startAt.slice(0, 16), endAt: item.endAt.slice(0, 16), replacementCapacity: item.replacementCapacity, replacementStartTimeLocal: item.replacementStartTimeLocal, replacementEndTimeLocal: item.replacementEndTimeLocal, reason: item.reason}; feedback.value = "" }
const save = async () => { if (!form.value || !form.value.businessOfferingId || !form.value.startAt || !form.value.endAt) return; isSaving.value = true; error.value = ""; const request = {...form.value, startAt: new Date(form.value.startAt).toISOString(), endAt: new Date(form.value.endAt).toISOString()}; try { if (editingId.value) await userShellApi.updateBusinessAvailabilityException(editingId.value, request); else await userShellApi.createBusinessAvailabilityException(request); form.value = null; feedback.value = "Availability exception saved."; await load() } catch { error.value = "Could not save this exception." } finally { isSaving.value = false } }
const remove = async (item: BusinessAvailabilityExceptionResponseDTO) => { if (!window.confirm("Delete this availability exception?")) return; isSaving.value = true; error.value = ""; try { await userShellApi.deleteBusinessAvailabilityException(item.id); feedback.value = "Availability exception deleted."; await load() } catch { error.value = "Could not delete this exception." } finally { isSaving.value = false } }
onMounted(() => void load())
</script>

<template><section class="exceptions"><header class="exceptions__header"><div><p class="exceptions__eyebrow">Business / Availability</p><h1>Exceptions</h1></div><button type="button" class="exceptions__primary" :disabled="offerings.length === 0" @click="beginCreate">New exception</button></header><p v-if="feedback" class="exceptions__feedback" role="status">{{ feedback }}</p><div v-if="isLoading" class="exceptions__status" role="status">Loading.</div><div v-else-if="error && !form" class="exceptions__status exceptions__status--error" role="alert">{{ error }} <button type="button" @click="load">Retry</button></div><div v-else-if="items.length === 0 && !form" class="exceptions__status">No availability exceptions.</div><div v-else class="exceptions__list"><article v-for="item in items" :key="item.id" class="exceptions__row"><div><strong>{{ item.businessOfferingTitle }} · {{ item.exceptionType }}</strong><span>{{ formatDate(item.startAt) }} – {{ formatDate(item.endAt) }}<template v-if="item.reason"> · {{ item.reason }}</template></span></div><div class="exceptions__actions"><button type="button" @click="beginEdit(item)">Edit</button><button type="button" class="exceptions__danger" @click="remove(item)">Delete</button></div></article></div><form v-if="form" class="exceptions__form" @submit.prevent="save"><h2>{{ editingId ? "Edit exception" : "New exception" }}</h2><label>Offering<select v-model.number="form.businessOfferingId" required><option v-for="offering in offerings" :key="offering.id" :value="offering.id">{{ offering.title }}</option></select></label><div class="exceptions__grid"><label>Type<select v-model="form.exceptionType"><option value="BLOCK">Block</option><option value="REPLACE_WINDOW">Replace window</option></select></label><label>Start<input v-model="form.startAt" type="datetime-local" required></label><label>End<input v-model="form.endAt" type="datetime-local" required></label></div><div v-if="form.exceptionType === 'REPLACE_WINDOW'" class="exceptions__grid"><label>Capacity<input v-model.number="form.replacementCapacity" type="number" min="1"></label><label>From<input v-model="form.replacementStartTimeLocal" type="time"></label><label>To<input v-model="form.replacementEndTimeLocal" type="time"></label></div><label>Reason<input v-model="form.reason" maxlength="500"></label><p v-if="error" class="exceptions__status exceptions__status--error" role="alert">{{ error }}</p><div><button type="submit" class="exceptions__primary" :disabled="isSaving">{{ isSaving ? "Saving" : "Save" }}</button><button type="button" class="exceptions__secondary" @click="form = null">Cancel</button></div></form></section></template>

<style scoped>
.exceptions{display:grid;gap:1rem;max-width:56rem}.exceptions__header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.exceptions__eyebrow{margin:0 0 .3rem;color:rgba(23,34,26,.55);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem);letter-spacing:-.075em}h2{margin:0;font-size:1.1rem}.exceptions__list{display:grid;gap:.45rem}.exceptions__row{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:.85rem 0;border-bottom:1px solid rgba(23,34,26,.08)}.exceptions__row>div:first-child{display:grid;gap:.3rem}.exceptions__row span{color:rgba(23,34,26,.58);font-size:.84rem}.exceptions__actions{display:flex;gap:.35rem}.exceptions button{border:1px solid rgba(23,34,26,.12);border-radius:999px;padding:.45rem .75rem;background:transparent;font:inherit;font-size:.82rem;font-weight:650;cursor:pointer;white-space:nowrap}.exceptions__primary{border:0!important;background:#17221a!important;color:#f8f8f4}.exceptions__primary:disabled{opacity:.5;cursor:not-allowed}.exceptions__danger{color:#8d2f25}.exceptions__secondary{margin-left:.4rem}.exceptions__form{display:grid;gap:.75rem;border-top:1px solid rgba(23,34,26,.1);padding-top:1rem}.exceptions__form label{display:grid;gap:.35rem;font-size:.83rem;font-weight:650}.exceptions__form input,.exceptions__form select{border:1px solid rgba(23,34,26,.14);border-radius:.65rem;padding:.65rem;font:inherit}.exceptions__grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem}.exceptions__feedback{margin:0;color:#2d6846}.exceptions__status{padding:.7rem 0;color:rgba(23,34,26,.65)}.exceptions__status--error{color:#8d2f25}.exceptions__status button{margin-left:.5rem;border:0;background:none;color:inherit;text-decoration:underline}@media(max-width:620px){.exceptions__row{align-items:start;flex-direction:column}.exceptions__grid{grid-template-columns:1fr}}
</style>
