<script setup lang="ts">
import {onMounted, ref} from "vue"
import {RouterLink} from "vue-router"
import type {BusinessProfileResponseDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
const items = ref<BusinessProfileResponseDTO[]>([]); const query = ref(""); const isLoading = ref(true); const error = ref("")
const load = async () => { isLoading.value = true; error.value = ""; try { items.value = (await userShellApi.getBusinessDirectory(query.value.trim())).items } catch { error.value = "Could not load businesses." } finally { isLoading.value = false } }
const search = async () => { await load() }
onMounted(() => void load())
</script>
<template><section class="business-discovery"><header><div><p class="eyebrow">Business / Discover</p><h1>Find a business</h1><p class="intro">Browse public businesses and open their booking pages.</p></div><RouterLink to="/business" class="secondary">My business</RouterLink></header><form class="search-form" @submit.prevent="search"><input v-model="query" class="search" type="search" placeholder="Search businesses" aria-label="Search businesses"><button type="submit" class="primary" :disabled="isLoading">{{ isLoading ? "Searching" : "Search" }}</button></form><p v-if="isLoading" class="status" role="status">Loading businesses.</p><p v-else-if="error" class="status status--error" role="alert">{{ error }} <button type="button" @click="load">Retry</button></p><p v-else-if="items.length === 0" class="status">No public businesses match this search.</p><div v-else class="results"><article v-for="business in items" :key="business.id" class="result"><div><strong>{{ business.businessName }}</strong><p>{{ business.headline || business.description || "Public business profile" }}</p><span>{{ business.bookingEnabled ? "Bookings available" : "Profile only" }}</span></div><RouterLink :to="`/business/public/${business.slug}`" class="primary">View business</RouterLink></article></div></section></template>
<style scoped>.business-discovery{display:grid;gap:1rem;max-width:58rem}.business-discovery header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.eyebrow{margin:0 0 .3rem;color:rgba(23,34,26,.55);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.7rem,3vw,2.6rem);letter-spacing:-.075em}.intro{color:rgba(23,34,26,.62)}.search-form{display:flex;gap:.45rem;max-width:42rem}.search{width:100%;border:1px solid rgba(23,34,26,.14);border-radius:.7rem;padding:.7rem;font:inherit}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;border:1px solid rgba(23,34,26,.14);border-radius:999px;padding:.55rem .8rem;font:inherit;font-size:.8rem;font-weight:650}.primary{background:#17221a;color:#f8f8f4}.results{display:grid;gap:.4rem}.result{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem;border:1px solid rgba(23,34,26,.08);border-radius:.9rem;background:rgba(255,255,255,.62)}.result p,.result span{display:block;margin:.25rem 0 0;color:rgba(23,34,26,.6);font-size:.84rem}.status{color:rgba(23,34,26,.62)}.status--error{color:#8d2f25}.status button{margin-left:.5rem;border:0;background:none;color:inherit;text-decoration:underline}@media(max-width:620px){.business-discovery header,.result{align-items:start;flex-direction:column}.search-form{max-width:none;width:100%}}</style>
