<script setup lang="ts">
import {onMounted, ref} from "vue"
import {useRoute} from "vue-router"
import type {BusinessPublicPageDTO, BusinessBookingRequestDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import AppDialog from "../components/AppDialog.vue"

const route = useRoute()
const page = ref<BusinessPublicPageDTO | null>(null)
const selectedOfferingId = ref<number | null>(null)
const startsAt = ref("")
const customerNote = ref("")
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref("")
const feedback = ref("")
const bookingFeedback = ref("")
const bookingError = ref("")
const isFavorite = ref(false)
const isFavoriteActing = ref(false)
const load = async () => { isLoading.value = true; error.value = ""; try { page.value = await userShellApi.getPublicBusinessPage(String(route.params.slug)); try { const favorites = await userShellApi.getBusinessFavorites(); isFavorite.value = favorites.some(item => item.businessProfileId === page.value?.businessProfileId) } catch { isFavorite.value = false } } catch { error.value = "Could not load this business." } finally { isLoading.value = false } }
const toggleFavorite = async () => { if (!page.value) return; isFavoriteActing.value = true; error.value = ""; try { if (isFavorite.value) await userShellApi.removeBusinessFavorite(page.value.businessProfileId); else await userShellApi.addBusinessFavorite(page.value.businessProfileId); isFavorite.value = !isFavorite.value; feedback.value = isFavorite.value ? "Business saved to favorites." : "Business removed from favorites." } catch { error.value = "Could not update business favorites." } finally { isFavoriteActing.value = false } }
const book = async () => { if (!page.value || !selectedOfferingId.value || !startsAt.value) return; isSaving.value = true; bookingError.value = ""; bookingFeedback.value = ""; const start = new Date(startsAt.value).toISOString(); try { const preview = await userShellApi.previewPublicBooking(String(route.params.slug), {businessOfferingId: selectedOfferingId.value, startsAt: start}); const request: BusinessBookingRequestDTO = {businessOfferingId: preview.businessOfferingId, startsAt: preview.startsAt, endsAt: preview.endsAt, customerNote: customerNote.value, idempotencyKey: crypto.randomUUID()}; await userShellApi.createCustomerBooking(request); bookingFeedback.value = "Booking request sent."; customerNote.value = "" } catch { bookingError.value = "Could not create this booking." } finally { isSaving.value = false } }
onMounted(() => void load())
</script>

<template><section class="public-business"><div v-if="isLoading" class="public-business__status" role="status">Loading.</div><div v-else-if="error && !page" class="public-business__status public-business__status--error" role="alert">{{ error }} <button type="button" @click="load">Retry</button></div><template v-else-if="page"><header><p class="public-business__eyebrow">Business</p><div class="public-business__title-row"><div><h1>{{ page.businessName }}</h1><p class="public-business__headline">{{ page.headline }}</p></div><button type="button" class="public-business__favorite" :disabled="isFavoriteActing" @click="toggleFavorite">{{ isFavorite ? "Saved" : "Save business" }}</button></div><p>{{ page.description }}</p></header><p v-if="feedback" class="public-business__feedback" role="status">{{ feedback }}</p><p v-if="error" class="public-business__status public-business__status--error" role="alert">{{ error }}</p><div class="public-business__offerings"><article v-for="offering in page.offerings" :key="offering.id" class="public-business__offering"><strong>{{ offering.title }}</strong><span>{{ offering.summary }} · {{ offering.basePriceAmount }} {{ offering.basePriceCurrency }} · {{ offering.defaultDurationMinutes }} min</span><button type="button" @click="selectedOfferingId = offering.id; bookingFeedback = ''; bookingError = ''">Book</button></article></div><AppDialog :open="selectedOfferingId !== null" title="Request a booking" @close="selectedOfferingId = null"><form class="public-business__form" @submit.prevent="book"><label>Start<input v-model="startsAt" type="datetime-local" required></label><label>Note<textarea v-model="customerNote" maxlength="2000"></textarea></label><p v-if="bookingFeedback" class="public-business__feedback" role="status">{{ bookingFeedback }}</p><p v-if="bookingError" class="public-business__status public-business__status--error" role="alert">{{ bookingError }}</p><button type="submit" :disabled="isSaving">{{ isSaving ? "Sending" : "Send request" }}</button></form></AppDialog></template></section></template>

<style scoped>
.public-business{display:grid;gap:1.2rem;max-width:52rem}.public-business__eyebrow{margin:0 0 .3rem;color:rgba(23,34,26,.55);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.7rem,3vw,2.6rem);letter-spacing:-.075em}.public-business__title-row{display:flex;align-items:start;justify-content:space-between;gap:1rem}.public-business__headline{color:rgba(23,34,26,.65)}.public-business__offerings{display:grid;gap:.45rem}.public-business__offering{display:flex;align-items:center;gap:1rem;padding:.85rem 0;border-bottom:1px solid rgba(23,34,26,.08)}.public-business__offering strong{margin-right:auto}.public-business__offering span{color:rgba(23,34,26,.58);font-size:.84rem}.public-business button{border:1px solid rgba(23,34,26,.12);border-radius:999px;padding:.45rem .75rem;background:#17221a;color:#f8f8f4;font:inherit;font-size:.82rem;font-weight:650;cursor:pointer}.public-business__favorite{background:rgba(214,228,218,.8)!important;color:#17221a!important}.public-business__form{display:grid;gap:.75rem;border-top:1px solid rgba(23,34,26,.1);padding-top:1rem;max-width:32rem}.public-business__form label{display:grid;gap:.35rem;font-size:.83rem;font-weight:650}.public-business__form input,.public-business__form textarea{border:1px solid rgba(23,34,26,.14);border-radius:.65rem;padding:.65rem;font:inherit}.public-business__form textarea{min-height:5rem}.public-business__feedback{color:#2d6846}.public-business__status{padding:.7rem 0;color:rgba(23,34,26,.65)}.public-business__status--error{color:#8d2f25}.public-business__status button{margin-left:.5rem;background:none;color:inherit;text-decoration:underline}@media(max-width:620px){.public-business__title-row{align-items:start;flex-direction:column}.public-business__offering{align-items:start;flex-wrap:wrap}.public-business__offering span{width:100%}}
</style>
