<script setup lang="ts">
import {computed, onMounted, ref, watch} from "vue"
import {RouterLink} from "vue-router"
import type {BusinessAvailabilityRuleRequestDTO, BusinessAvailabilityRuleResponseDTO, BusinessOfferingResponseDTO, BusinessWorkspaceContextDTO} from "../../../contracts/index.ts"
import {userShellApi, setActiveBusinessProfileId, type OperatorDashboardSections} from "../api/userShellApi.ts"
import AppDialog from "../components/AppDialog.vue"
import AppButton from "../components/AppButton.vue"
import AppFormField from "../components/AppFormField.vue"
import AppFormFooter from "../components/AppFormFooter.vue"
import AppStatus from "../components/AppStatus.vue"
import ContextSwitcher from "../components/ContextSwitcher.vue"
import TaskSurface from "../components/TaskSurface.vue"
import {formatDateTime} from "../../../services/formatters.ts"

const context = ref<BusinessWorkspaceContextDTO | null>(null)
const selectedProfileId = ref<number | null>(null)
const roleFilter = ref<"ALL" | "OWNER" | "CUSTOMER">("ALL")
const calendarScope = ref<"MY" | "BUSINESS" | "ALL">("MY")
const calendarLayers = ref({bookings: true, availability: false, resources: false})
const showRules = ref(false)
const rules = ref<BusinessAvailabilityRuleResponseDTO[]>([])
const offerings = ref<BusinessOfferingResponseDTO[]>([])
const form = ref<BusinessAvailabilityRuleRequestDTO | null>(null)
const editingId = ref<number | null>(null)
const loading = ref(true)
const saving = ref(false)
const error = ref("")
const feedback = ref("")
const operatorSections = ref<OperatorDashboardSections>({bookings: true, revenue: true, staffWorkload: true, availabilityGaps: true, pendingRequests: true, customerMessages: true})
const operatorSaving = ref(false)
const calendarOperationSaving = ref(false)
const operatorLabels: Record<keyof OperatorDashboardSections, string> = {bookings: "Bookings", revenue: "Revenue", staffWorkload: "Staff workload", availabilityGaps: "Availability gaps", pendingRequests: "Pending requests", customerMessages: "Customer messages"}
const businessOptions = computed(() => [{id: "ALL", label: "All businesses", description: "Aggregate owner and customer schedule"}, ...(context.value?.businesses ?? []).map(item => ({id: item.id, label: item.businessName}))])
const selectedContextId = computed(() => selectedProfileId.value === null ? "ALL" : selectedProfileId.value)
// The agenda is booking-first; availability is intentionally an optional operational layer.
const schedule = computed(() => (context.value?.schedule ?? []).filter(item => (calendarScope.value !== "BUSINESS" || item.role === "OWNER") && (roleFilter.value === "ALL" || item.role === roleFilter.value)).sort((a, b) => a.startsAt.localeCompare(b.startsAt)))
const calendarScopeDescription = computed(() => calendarScope.value === "MY" ? "Your bookings and business work" : calendarScope.value === "BUSINESS" ? "Bookings managed by this business" : "Combined schedule across permitted businesses")
const capacityWarning = computed(() => schedule.value.length > 20 ? "High booking density: review capacity and resource allocation before accepting more work." : schedule.value.length === 0 ? "No booking rows in this scope; unavailable time may be caused by hours, exceptions, capacity, resources, policy, or conflict." : "Capacity is within the loaded schedule window; server availability remains authoritative.")
const groupedSchedule = computed(() => {
  if (!calendarLayers.value.bookings) return []
  const groups = new Map<string, typeof schedule.value>()
  schedule.value.forEach(item => { const key = item.startsAt.slice(0, 10); groups.set(key, [...(groups.get(key) ?? []), item]) })
  return [...groups.entries()].map(([date, items]) => ({date, items}))
})
const today = () => new Date().toISOString().slice(0, 10)
const range = () => { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 45); return {from: from.toISOString(), to: to.toISOString()} }
const load = async () => { loading.value = true; error.value = ""; try { const [next, sections] = await Promise.all([userShellApi.getBusinessWorkspaceContext({...range(), profileId: selectedProfileId.value}), userShellApi.getOperatorDashboardSections()]); context.value = next; operatorSections.value = sections; selectedProfileId.value = next.activeBusinessProfileId; if (selectedProfileId.value) setActiveBusinessProfileId(selectedProfileId.value) } catch { error.value = "Could not load your business schedule." } finally { loading.value = false } }
const saveOperatorSections = async () => { operatorSaving.value = true; try { operatorSections.value = await userShellApi.updateOperatorDashboardSections(operatorSections.value); feedback.value = "Operator dashboard layout saved on this device." } finally { operatorSaving.value = false } }
const runCalendarOperation = async (action: "confirm" | "reject" | "cancel" | "complete" | "mark-no-show") => { const bookingId = schedule.value.find(item => item.role === "OWNER")?.bookingId; if (!bookingId) { feedback.value = "No owner booking is available for this operation."; return } calendarOperationSaving.value = true; error.value = ""; try { await userShellApi.executeCalendarBookingAction(bookingId, action); feedback.value = `Booking ${action.replace('-', ' ')} request sent.`; await load() } catch { error.value = "The booking changed or is no longer actionable. Refresh before retrying." } finally { calendarOperationSaving.value = false } }
const loadRules = async () => { if (!selectedProfileId.value) return; try { const [ruleResponse, offeringResponse] = await Promise.all([userShellApi.getBusinessAvailabilityRules(), userShellApi.getBusinessOfferings()]); rules.value = ruleResponse.items; offerings.value = offeringResponse.items } catch { error.value = "Could not load availability layers." } }
const selectBusiness = async (value: string | number | null) => { selectedProfileId.value = value === null || value === "ALL" ? null : Number(value); setActiveBusinessProfileId(selectedProfileId.value); await load() }
const emptyForm = (): BusinessAvailabilityRuleRequestDTO => ({businessOfferingId: offerings.value[0]?.id ?? 0, dayOfWeek: 1, startTimeLocal: "09:00", endTimeLocal: "17:00", slotGranularityMinutes: 60, capacityOverride: 1, validFrom: today(), validUntil: "", active: true})
const beginCreate = () => { editingId.value = null; form.value = emptyForm(); feedback.value = "" }
const beginEdit = (rule: BusinessAvailabilityRuleResponseDTO) => { editingId.value = rule.id; form.value = {businessOfferingId: rule.businessOfferingId, dayOfWeek: rule.dayOfWeek, startTimeLocal: rule.startTimeLocal, endTimeLocal: rule.endTimeLocal, slotGranularityMinutes: rule.slotGranularityMinutes, capacityOverride: rule.capacityOverride, validFrom: rule.validFrom, validUntil: rule.validUntil, active: rule.active} }
const save = async () => { if (!form.value || !form.value.businessOfferingId) return; saving.value = true; error.value = ""; try { if (editingId.value) await userShellApi.updateBusinessAvailabilityRule(editingId.value, form.value); else await userShellApi.createBusinessAvailabilityRule(form.value); form.value = null; feedback.value = "Availability rule saved."; await loadRules() } catch { error.value = "Could not save this availability rule." } finally { saving.value = false } }
onMounted(() => void load())
watch(showRules, value => { if (value) void loadRules() })
</script>

<template>
  <TaskSurface mode="choose" label="Business schedule">
    <section class="business-calendar">
      <header class="business-calendar__header"><div><p class="eyebrow">Business / Schedule</p><h1>My schedule</h1><p class="intro">Bookings are the main view. Availability and resources are optional layers.</p></div><ContextSwitcher :model-value="selectedContextId" :options="businessOptions" label="Active business" empty-label="All businesses" @update:model-value="selectBusiness" /></header>
      <AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error" :message="error" tone="error" retry @retry="load" /><AppStatus v-if="loading" message="Loading your schedule." busy />
      <template v-else>
        <section class="calendar-intelligence" aria-label="Capacity and availability explanation"><strong>Capacity intelligence</strong><span>{{ capacityWarning }}</span><small>Why unavailable? The backend evaluates business hours, exceptions, capacity, resources, policy, and conflicting bookings. This screen does not infer a slot as bookable.</small><div class="capacity-heatmap" aria-label="Loaded booking density"><i v-for="index in 7" :key="index" :class="{active: schedule.length >= index * 3, warning: schedule.length >= index * 5}" :title="`Density band ${index}`"></i></div></section>
        <section class="calendar-operations" aria-label="Calendar operations"><strong>Booking operations</strong><small>Actions run against the selected business schedule and may be rejected if the booking is stale or conflicted.</small><div><AppButton type="button" tone="secondary" :loading="calendarOperationSaving" @click="runCalendarOperation('confirm')">Confirm</AppButton><AppButton type="button" tone="secondary" :loading="calendarOperationSaving" @click="runCalendarOperation('complete')">Complete</AppButton><AppButton type="button" tone="secondary" :loading="calendarOperationSaving" @click="runCalendarOperation('mark-no-show')">Mark no-show</AppButton><AppButton type="button" tone="danger" :loading="calendarOperationSaving" @click="runCalendarOperation('cancel')">Cancel</AppButton></div></section>
        <section class="calendar-scopes" aria-label="Calendar scope"><strong>Calendar scope</strong><div><label><input v-model="calendarScope" type="radio" value="MY"> My schedule</label><label><input v-model="calendarScope" type="radio" value="BUSINESS"> Business schedule</label><label><input v-model="calendarScope" type="radio" value="ALL"> All businesses</label></div><small>{{ calendarScopeDescription }}</small></section>
        <section class="calendar-layers" aria-label="Calendar layers"><strong>Layers</strong><label><input v-model="calendarLayers.bookings" type="checkbox"> Booking rows</label><label><input v-model="calendarLayers.availability" type="checkbox"> Availability blocks</label><label><input v-model="calendarLayers.resources" type="checkbox"> Employee/resource allocation</label><small v-if="calendarLayers.resources">Resource allocation is shown only when the backend supplies permitted staff or resource data.</small></section>
        <section class="operator-dashboard" aria-label="Operator dashboard sections"><header><div><p class="eyebrow">Operator dashboard</p><h2>Choose the sections you need</h2><small>Owner-side layout only; values and permissions remain server-authoritative.</small></div><AppButton type="button" tone="secondary" :loading="operatorSaving" @click="saveOperatorSections">Save layout</AppButton></header><div class="operator-dashboard__options"><label v-for="key in Object.keys(operatorSections) as Array<keyof OperatorDashboardSections>" :key="key"><input v-model="operatorSections[key]" type="checkbox"> {{ operatorLabels[key] }}</label></div><div class="operator-dashboard__summary"><span v-if="operatorSections.bookings">Bookings: {{ schedule.length }} in next 45 days.</span><span v-if="operatorSections.revenue">Revenue: available from backend financial reporting when configured.</span><span v-if="operatorSections.staffWorkload">Staff workload: available when staff/resources are configured.</span><span v-if="operatorSections.availabilityGaps">Availability gaps: inspect availability rules and exceptions.</span><span v-if="operatorSections.pendingRequests">Pending requests: shown when business requests exist.</span><span v-if="operatorSections.customerMessages">Customer messages: open shared Chat for conversation context.</span></div></section>
        <section class="schedule-toolbar" aria-label="Schedule filters"><div><strong>{{ schedule.length }}</strong><span>appointments in the next 45 days</span></div><label>Show <select v-model="roleFilter"><option value="ALL">Everything</option><option value="OWNER">I manage</option><option value="CUSTOMER">I booked</option></select></label><AppButton type="button" tone="secondary" @click="showRules = !showRules">{{ showRules ? "Hide availability" : "Availability layer" }}</AppButton><RouterLink to="/business/availability-exceptions">Exceptions</RouterLink></section>
        <section v-if="groupedSchedule.length" class="schedule-agenda" aria-label="Booking agenda"><article v-for="group in groupedSchedule" :key="group.date"><h2>{{ new Date(`${group.date}T12:00:00`).toLocaleDateString(undefined, {weekday: "long", month: "short", day: "numeric"}) }}</h2><ul><li v-for="item in group.items" :key="`${item.role}-${item.bookingId}`"><div><strong>{{ item.businessOfferingTitle }}</strong><span>{{ formatDateTime(item.startsAt, "Unknown time") }} – {{ formatDateTime(item.endsAt, "Unknown time") }}</span></div><div class="schedule-item__meta"><span>{{ item.businessName }}</span><span>{{ item.role === "OWNER" ? "Managed by me" : "Booked by me" }}</span><span>{{ item.statusLabel }}</span></div></li></ul></article></section><AppStatus v-else message="No appointments in this window." />
        <section v-if="showRules" class="availability-layer"><header><div><p class="eyebrow">Optional layer</p><h2>Availability rules</h2></div><AppButton type="button" tone="primary" :disabled="!offerings.length" @click="beginCreate">New rule</AppButton></header><ul><li v-for="rule in rules" :key="rule.id"><div><strong>{{ rule.businessOfferingTitle }}</strong><span>{{ rule.startTimeLocal }}–{{ rule.endTimeLocal }} · capacity {{ rule.capacityOverride }}</span></div><AppButton type="button" tone="quiet" @click="beginEdit(rule)">Edit</AppButton></li></ul></section>
      </template>
      <AppDialog :open="form !== null" :title="editingId ? 'Edit availability rule' : 'New availability rule'" layout="workspace" @close="form = null"><form v-if="form" class="rule-form" @submit.prevent="save"><AppFormField label="Offering" required><select v-model.number="form.businessOfferingId" required><option v-for="offering in offerings" :key="offering.id" :value="offering.id">{{ offering.title }}</option></select></AppFormField><div class="rule-form__grid"><AppFormField label="Day"><input v-model.number="form.dayOfWeek" type="number" min="1" max="7"></AppFormField><AppFormField label="From" required><input v-model="form.startTimeLocal" type="time" required></AppFormField><AppFormField label="To" required><input v-model="form.endTimeLocal" type="time" required></AppFormField></div><div class="rule-form__grid"><AppFormField label="Slot minutes"><input v-model.number="form.slotGranularityMinutes" type="number" min="1"></AppFormField><AppFormField label="Capacity"><input v-model.number="form.capacityOverride" type="number" min="1"></AppFormField><AppFormField label="Valid from"><input v-model="form.validFrom" type="date" required></AppFormField></div><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" @click="form = null">Cancel</AppButton></template><template #primary><AppButton type="submit" tone="primary" :loading="saving">Save rule</AppButton></template></AppFormFooter></form></AppDialog>
    </section>
  </TaskSurface>
</template>

<style scoped>
.business-calendar{display:grid;gap:var(--space-3);max-width:70rem}.business-calendar__header{display:flex;justify-content:space-between;align-items:end;gap:var(--space-3)}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1,h2,p{margin:0}.intro{max-width:38rem;color:var(--text-muted);margin-top:var(--space-1)}.schedule-toolbar{display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap;padding:var(--space-2) var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.schedule-toolbar>div{display:grid;margin-right:auto}.schedule-toolbar>div span{color:var(--text-muted);font-size:var(--text-size-meta)}.schedule-toolbar label{display:inline-flex;align-items:center;gap:var(--space-1);color:var(--text-muted);font-size:var(--text-size-meta)}select{border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.schedule-agenda{display:grid;gap:var(--space-3)}.schedule-agenda article,.availability-layer{border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base);overflow:hidden}.schedule-agenda h2{padding:var(--space-2) var(--space-3);font-size:var(--text-size-title);border-bottom:1px solid var(--border-subtle)}ul{list-style:none;margin:0;padding:0}.schedule-agenda li,.availability-layer li{display:flex;justify-content:space-between;align-items:center;gap:var(--space-3);padding:var(--space-3);border-bottom:1px solid var(--border-subtle)}li:last-child{border-bottom:0}.schedule-agenda li>div:first-child,.availability-layer li>div{display:grid;gap:var(--space-1)}.schedule-agenda li span,.availability-layer li span{color:var(--text-muted);font-size:var(--text-size-meta)}.schedule-item__meta{display:flex;gap:var(--space-2);flex-wrap:wrap;justify-content:flex-end;text-align:right}.availability-layer{display:grid;gap:0}.availability-layer header{display:flex;align-items:center;justify-content:space-between;padding:var(--space-3);border-bottom:1px solid var(--border-subtle)}.rule-form{display:grid;gap:var(--space-3)}.rule-form__grid{display:grid;grid-template-columns:repeat(3,1fr);gap:var(--space-2)}@media(max-width:760px){.business-calendar__header{align-items:start;flex-direction:column}.schedule-toolbar>div{width:100%;margin-right:0}.schedule-agenda li{align-items:start;flex-direction:column}.schedule-item__meta{justify-content:flex-start;text-align:left}.rule-form__grid{grid-template-columns:1fr}}
</style>
<style scoped>
.calendar-intelligence{display:grid;gap:var(--space-1);padding:var(--space-2) var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.calendar-intelligence span,.calendar-intelligence small{color:var(--text-muted)}.capacity-heatmap{display:grid;grid-template-columns:repeat(7,minmax(1rem,1fr));gap:var(--space-1);max-width:20rem}.capacity-heatmap i{height:.55rem;border-radius:999px;background:var(--border-subtle)}.capacity-heatmap i.active{background:var(--accent)}.capacity-heatmap i.warning{background:var(--warning)}
</style>
<style scoped>
.calendar-operations{display:grid;gap:var(--space-1);padding:var(--space-2) var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.calendar-operations small{color:var(--text-muted)}.calendar-operations>div{display:flex;gap:var(--space-1);flex-wrap:wrap}
</style>
<style scoped>
.calendar-layers{display:flex;gap:var(--space-2);align-items:center;flex-wrap:wrap;padding:var(--space-2) var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.calendar-layers strong{margin-right:auto}.calendar-layers label{display:inline-flex;align-items:center;gap:var(--space-1);font-size:var(--text-size-meta)}.calendar-layers small{flex-basis:100%;color:var(--text-muted)}
</style>
<style scoped>
.calendar-scopes{display:grid;gap:var(--space-1);padding:var(--space-2) var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.calendar-scopes>div{display:flex;gap:var(--space-3);flex-wrap:wrap}.calendar-scopes label{display:inline-flex;align-items:center;gap:var(--space-1);font-weight:var(--text-weight-semibold)}.calendar-scopes small{color:var(--text-muted)}
</style>
<style scoped>
.operator-dashboard{display:grid;gap:var(--space-2);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.operator-dashboard header{display:flex;justify-content:space-between;gap:var(--space-2);align-items:start}.operator-dashboard header small,.operator-dashboard__summary{color:var(--text-muted)}.operator-dashboard__options{display:flex;flex-wrap:wrap;gap:var(--space-2)}.operator-dashboard__options label{padding:var(--space-1) var(--space-2);border:1px solid var(--border-subtle);border-radius:var(--radius-control)}.operator-dashboard__summary{display:grid;gap:var(--space-1);font-size:var(--text-size-meta)}
</style>
