<script setup lang="ts">
import {onMounted, ref} from "vue"
import type {BusinessAvailabilityRuleRequestDTO, BusinessAvailabilityRuleResponseDTO, BusinessOfferingResponseDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import AppDialog from "../components/AppDialog.vue"
import {confirmAction} from "../composables/useActionDialog.ts"

const rules = ref<BusinessAvailabilityRuleResponseDTO[]>([])
const offerings = ref<BusinessOfferingResponseDTO[]>([])
const form = ref<BusinessAvailabilityRuleRequestDTO | null>(null)
const editingId = ref<number | null>(null)
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref("")
const feedback = ref("")
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
const today = () => new Date().toISOString().slice(0, 10)
const emptyForm = (): BusinessAvailabilityRuleRequestDTO => ({businessOfferingId: offerings.value[0]?.id ?? 0, dayOfWeek: 1, startTimeLocal: "09:00", endTimeLocal: "17:00", slotGranularityMinutes: 60, capacityOverride: 1, validFrom: today(), validUntil: "", active: true})
const load = async () => { isLoading.value = true; error.value = ""; try { const [ruleResponse, offeringResponse] = await Promise.all([userShellApi.getBusinessAvailabilityRules(), userShellApi.getBusinessOfferings()]); rules.value = ruleResponse.items; offerings.value = offeringResponse.items } catch { error.value = "Could not load availability." } finally { isLoading.value = false } }
const beginCreate = () => { editingId.value = null; form.value = emptyForm(); feedback.value = "" }
const beginEdit = (rule: BusinessAvailabilityRuleResponseDTO) => { editingId.value = rule.id; form.value = {businessOfferingId: rule.businessOfferingId, dayOfWeek: rule.dayOfWeek, startTimeLocal: rule.startTimeLocal, endTimeLocal: rule.endTimeLocal, slotGranularityMinutes: rule.slotGranularityMinutes, capacityOverride: rule.capacityOverride, validFrom: rule.validFrom, validUntil: rule.validUntil, active: rule.active}; feedback.value = "" }
const save = async () => { if (!form.value || !form.value.businessOfferingId) return; isSaving.value = true; error.value = ""; try { if (editingId.value) await userShellApi.updateBusinessAvailabilityRule(editingId.value, form.value); else await userShellApi.createBusinessAvailabilityRule(form.value); form.value = null; feedback.value = "Availability rule saved."; await load() } catch { error.value = "Could not save this availability rule." } finally { isSaving.value = false } }
const remove = async (rule: BusinessAvailabilityRuleResponseDTO) => { if (!await confirmAction("Delete this availability rule?", "Delete availability rule")) return; isSaving.value = true; error.value = ""; try { await userShellApi.deleteBusinessAvailabilityRule(rule.id); feedback.value = "Availability rule deleted."; await load() } catch { error.value = "Could not delete this availability rule." } finally { isSaving.value = false } }
onMounted(() => void load())
</script>

<template>
  <section class="availability-surface"><header class="availability-surface__header"><div><p class="availability-surface__eyebrow">Business / Availability</p><h1>Availability</h1></div><button type="button" class="availability-surface__primary" :disabled="offerings.length === 0" @click="beginCreate">New rule</button></header><p v-if="feedback" class="availability-surface__feedback" role="status">{{ feedback }}</p><div v-if="isLoading" class="availability-surface__status" role="status">Loading.</div><div v-else-if="error && !form" class="availability-surface__status availability-surface__status--error" role="alert">{{ error }} <button type="button" @click="load">Retry</button></div><div v-else-if="rules.length === 0 && !form" class="availability-surface__status">No availability rules yet.</div><div v-else class="availability-surface__list"><article v-for="rule in rules" :key="rule.id" class="availability-surface__row"><div><strong>{{ rule.businessOfferingTitle }}</strong><span>{{ days[rule.dayOfWeek - 1] }} · {{ rule.startTimeLocal }}–{{ rule.endTimeLocal }} · capacity {{ rule.capacityOverride }}</span></div><div class="availability-surface__actions"><button type="button" @click="beginEdit(rule)">Edit</button><button type="button" class="availability-surface__danger" @click="remove(rule)">Delete</button></div></article></div><AppDialog :open="form !== null" :title="editingId ? 'Edit rule' : 'New rule'" @close="form = null"><form class="availability-surface__form" @submit.prevent="save"><label>Offering<select v-model.number="form!.businessOfferingId" required><option v-for="offering in offerings" :key="offering.id" :value="offering.id">{{ offering.title }}</option></select></label><div class="availability-surface__grid"><label>Day<select v-model.number="form!.dayOfWeek"><option v-for="(day, index) in days" :key="day" :value="index + 1">{{ day }}</option></select></label><label>From<input v-model="form!.startTimeLocal" type="time" required></label><label>To<input v-model="form!.endTimeLocal" type="time" required></label></div><div class="availability-surface__grid"><label>Slot minutes<input v-model.number="form!.slotGranularityMinutes" type="number" min="1"></label><label>Capacity<input v-model.number="form!.capacityOverride" type="number" min="1"></label><label>Valid from<input v-model="form!.validFrom" type="date" required></label></div><label class="availability-surface__toggle"><input v-model="form!.active" type="checkbox"> Active</label><p v-if="error" class="availability-surface__status availability-surface__status--error" role="alert">{{ error }}</p><div><button type="submit" class="availability-surface__primary" :disabled="isSaving">{{ isSaving ? "Saving" : "Save" }}</button><button type="button" class="availability-surface__secondary" @click="form = null">Cancel</button></div></form></AppDialog></section>
</template>

<style scoped>
.availability-surface{display:grid;gap:1rem;max-width:54rem}.availability-surface__header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.availability-surface__eyebrow{margin:0 0 .3rem;color:rgba(23,34,26,.55);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem);letter-spacing:-.075em}h2{margin:0;font-size:1.1rem}.availability-surface__list{display:grid;gap:.45rem}.availability-surface__row{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:.85rem 0;border-bottom:1px solid rgba(23,34,26,.08)}.availability-surface__row>div:first-child{display:grid;gap:.28rem}.availability-surface__row span{color:rgba(23,34,26,.58);font-size:.84rem}.availability-surface__actions{display:flex;gap:.35rem}.availability-surface button{border:1px solid rgba(23,34,26,.12);border-radius:999px;padding:.45rem .75rem;background:transparent;font:inherit;font-size:.82rem;font-weight:650;cursor:pointer;white-space:nowrap}.availability-surface__primary{border:0!important;background:#17221a!important;color:#f8f8f4}.availability-surface__primary:disabled{opacity:.5;cursor:not-allowed}.availability-surface__danger{color:#8d2f25}.availability-surface__secondary{margin-left:.4rem}.availability-surface__form{display:grid;gap:.75rem;border-top:1px solid rgba(23,34,26,.1);padding-top:1rem}.availability-surface__form label{display:grid;gap:.35rem;font-size:.83rem;font-weight:650;color:rgba(23,34,26,.72)}.availability-surface__form input,.availability-surface__form select{border:1px solid rgba(23,34,26,.14);border-radius:.65rem;padding:.65rem;background:rgba(255,255,255,.55);font:inherit;font-weight:400}.availability-surface__grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem}.availability-surface__toggle{display:flex!important;align-items:center;gap:.5rem!important}.availability-surface__toggle input{width:auto}.availability-surface__feedback{margin:0;color:#2d6846}.availability-surface__status{padding:.7rem 0;color:rgba(23,34,26,.65)}.availability-surface__status--error{color:#8d2f25}.availability-surface__status button{margin-left:.5rem;border:0;background:none;color:inherit;text-decoration:underline}@media(max-width:620px){.availability-surface__row{align-items:start;flex-direction:column}.availability-surface__grid{grid-template-columns:1fr}}
</style>
