<script setup lang="ts">
import {computed, onMounted, ref} from "vue"
import type {NotificationPreferenceItemDTO, NotificationPreferenceUpdateDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import AppFormFooter from "../components/AppFormFooter.vue"
import AppButton from "../components/AppButton.vue"
import AppStatus from "../components/AppStatus.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
const items = ref<NotificationPreferenceItemDTO[]>([])
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref("")
const feedback = ref("")
const categories = computed(() => [...new Set(items.value.map(item => item.category))])
const labels: Record<string, string> = {CHAT: "Messages", WORK: "Work and applications", BOOKING: "Appointments", CIRCLE: "People and circles", LOCATION: "Location privacy", SYSTEM: "Account and safety"}
const load = async () => { isLoading.value = true; error.value = ""; try { items.value = (await userShellApi.getNotificationPreferences()).items } catch { error.value = "Could not load notification preferences." } finally { isLoading.value = false } }
const save = async () => { isSaving.value = true; error.value = ""; feedback.value = ""; try { const updates: NotificationPreferenceUpdateDTO[] = items.value.map(item => ({category: item.category, level: item.level, enabled: item.enabled})); items.value = (await userShellApi.updateNotificationPreferences(updates)).items; feedback.value = "Notification preferences saved." } catch { error.value = "Could not save notification preferences. Required system notices remain enabled." } finally { isSaving.value = false } }
onMounted(() => void load())
</script>
<template><section class="notification-preferences" data-mental-model="choose-life-area-choose-delivery"><header><p class="eyebrow">Profile / Settings</p><h1>Notifications</h1><p class="intro">Choose which parts of your life in the app can notify you. Account and safety notices stay on when the backend requires them.</p></header><CollectionToolbar title="Notification delivery" :count="items.length" :busy="isLoading" /><AppStatus v-if="isLoading" message="Loading notification preferences." busy /><AppStatus v-else-if="error" :message="error" tone="error" retry @retry="load" /><form v-else @submit.prevent="save"><fieldset v-for="category in categories" :key="category"><legend>{{ labels[category] || category }}</legend><label v-for="item in items.filter(value => value.category === category)" :key="`${item.category}-${item.level || 'default'}`" class="option"><input v-model="item.enabled" type="checkbox" :disabled="item.required || !item.available || isSaving"><span>{{ (item.level || 'Update').replace('_', ' ') }}<small v-if="item.required">Required to protect your account or keep you informed</small><small v-else-if="!item.available">{{ item.unavailableReason || 'This delivery option is not available right now' }}</small><small v-else-if="item.effectiveEnabled">Currently active</small></span></label></fieldset><AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error" :message="error" tone="error" /><AppFormFooter sticky><template #secondary><span>Only delivery options supported by the backend can be turned on.</span></template><template #primary><AppButton type="submit" tone="primary" :loading="isSaving">{{ isSaving ? "Saving" : "Save notification choices" }}</AppButton></template></AppFormFooter></form></section></template>
<style scoped>
.notification-preferences{display:grid;gap:var(--space-3);max-width:60rem}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1{margin:0;color:var(--text);font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}.intro{max-width:38rem;color:var(--text-muted)}form{display:grid;gap:var(--space-4);padding:0;border:0;background:transparent}fieldset{display:grid;gap:0;border:0;padding:0;margin:0}legend{width:100%;padding:0 0 var(--space-2);border-bottom:1px solid var(--border-subtle);color:var(--text);font-size:var(--text-size-title);font-weight:var(--text-weight-semibold)}.option{display:flex;align-items:center;gap:var(--space-2);min-height:var(--control-height-default);padding:var(--space-2) 0;border:0;border-bottom:1px solid var(--border-subtle);border-radius:0;color:var(--text);font-weight:var(--text-weight-medium)}.option:hover{background:var(--surface-hover)}.option input{width:1rem;height:1rem}.option span{display:grid;gap:.15rem;align-items:start}.option small,.app-form-footer__secondary{color:var(--text-soft);font-size:var(--text-size-meta)}
</style>
