<script setup lang="ts">
import {onMounted, ref} from "vue"
import {userShellApi, type OnboardingProgress} from "../api/userShellApi.ts"
const progress = ref<OnboardingProgress>({id: null, currentStep: "WELCOME", skipped: false, completed: false, updatedAt: null}); const error = ref(""); const feedback = ref("")
const load = async () => { try { progress.value = await userShellApi.getOnboardingProgress() } catch { error.value = "Could not load onboarding." } }
const save = async (step: string, skipped = false, completed = false) => { try { progress.value = await userShellApi.updateOnboardingProgress({currentStep: step, skipped, completed}); feedback.value = skipped ? "Onboarding skipped. Core product use remains available." : completed ? "Onboarding complete." : "Progress saved." } catch { error.value = "Could not save onboarding progress." } }
const reset = async () => { try { progress.value = await userShellApi.resetOnboardingProgress(); feedback.value = "Onboarding reset." } catch { error.value = "Could not reset onboarding." } }
onMounted(() => void load())
</script>
<template><section class="onboarding"><header><p class="eyebrow">Account / Setup</p><h1>Get oriented</h1><p>This setup is optional. You can skip it and use the product normally.</p></header><p v-if="feedback" class="success" role="status">{{ feedback }}</p><p v-if="error" class="error" role="alert">{{ error }}</p><div class="steps"><button v-for="step in ['WELCOME','PROFILE','PRIVACY','DISCOVER','DONE']" :key="step" type="button" :class="{active: progress.currentStep === step}" @click="save(step, false, step === 'DONE')">{{ step }}</button></div><p class="state">Current step: <strong>{{ progress.currentStep }}</strong><template v-if="progress.skipped"> · skipped</template></p><div class="actions"><button type="button" @click="save('WELCOME', true, false)">Skip setup</button><button type="button" @click="reset">Reset</button></div></section></template>
<style scoped>.onboarding{display:grid;gap:1rem;max-width:48rem}.eyebrow{margin:0 0 .3rem;color:var(--text-muted);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem)}header p:last-child,.state{color:var(--text-muted)}.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:.45rem}.steps button,.actions button{border:1px solid var(--border-subtle);border-radius:999px;padding:.55rem .7rem;background:transparent;font:inherit;cursor:pointer}.steps button.active{background:var(--accent);color:var(--text)}.actions{display:flex;gap:.45rem}.success{color:var(--success)}.error{color:var(--danger)}@media(max-width:600px){.steps{grid-template-columns:1fr 1fr}}</style>
