<script setup lang="ts">
import {onMounted, ref} from "vue"
import {userShellApi, type OnboardingProgress} from "../api/userShellApi.ts"
import AppFormFooter from "../components/AppFormFooter.vue"
import AppButton from "../components/AppButton.vue"
import AppStatus from "../components/AppStatus.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
const progress = ref<OnboardingProgress>({id: null, currentStep: "WELCOME", skipped: false, completed: false, updatedAt: null}); const error = ref(""); const feedback = ref(""); const isLoading = ref(true); const isSaving = ref(false)
// Setup progress is backend-owned; completion is explicit and separate from row selection.
const steps = [{id: "WELCOME", description: "Understand the workspace and its personal context."}, {id: "PROFILE", description: "Set the profile information you want others to see."}, {id: "PRIVACY", description: "Review location and relationship visibility."}, {id: "DISCOVER", description: "Open a product surface when you are ready."}, {id: "DONE", description: "Finish the optional setup."}]
const load = async () => { isLoading.value = true; error.value = ""; try { progress.value = await userShellApi.getOnboardingProgress() } catch { error.value = "Could not load onboarding." } finally { isLoading.value = false } }
const save = async (step: string, skipped = false, completed = false) => { isSaving.value = true; error.value = ""; try { progress.value = await userShellApi.updateOnboardingProgress({currentStep: step, skipped, completed}); feedback.value = skipped ? "Onboarding skipped. Core product use remains available." : completed ? "Onboarding complete." : "Progress saved." } catch { error.value = "Could not save onboarding progress." } finally { isSaving.value = false } }
const reset = async () => { isSaving.value = true; error.value = ""; try { progress.value = await userShellApi.resetOnboardingProgress(); feedback.value = "Onboarding reset." } catch { error.value = "Could not reset onboarding." } finally { isSaving.value = false } }
onMounted(() => void load())
</script>
<template><section class="onboarding"><header><p class="eyebrow">Account / Setup</p><h1>Get oriented</h1><p>This setup is optional. You can skip it and use the product normally.</p></header><CollectionToolbar title="Setup steps" :count="steps.length" :busy="isLoading" /><AppStatus v-if="isLoading" message="Loading onboarding progress." busy /><AppStatus v-else-if="error" :message="error" tone="error" retry @retry="load" /><template v-else><AppStatus v-if="feedback" :message="feedback" tone="success" /><p class="state">Current step: <strong>{{ progress.currentStep }}</strong><template v-if="progress.skipped"> · skipped</template></p><div class="steps"><SurfaceRow v-for="step in steps" :key="step.id" :row="{id: step.id, title: step.id, description: step.description, badge: progress.currentStep === step.id ? 'Current' : undefined}" :selected="progress.currentStep === step.id"><template #actions><AppButton type="button" :tone="step.id === 'DONE' ? 'primary' : 'secondary'" :loading="isSaving" @click="save(step.id, false, step.id === 'DONE')">{{ step.id === 'DONE' ? 'Complete' : 'Continue' }}</AppButton></template></SurfaceRow></div><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" :loading="isSaving" @click="reset">Reset</AppButton></template><template #primary><AppButton type="button" tone="quiet" :loading="isSaving" @click="save('WELCOME', true, false)">Skip setup</AppButton></template></AppFormFooter></template></section></template>
<style scoped>.onboarding{display:grid;gap:var(--space-3);max-width:60rem}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1{margin:0;color:var(--text);font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}header p:last-child,.state{margin:0;color:var(--text-muted)}.steps{overflow:hidden;border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.steps :deep(button){min-height:var(--control-height-default);border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:transparent;color:var(--text-muted);font:inherit;font-weight:var(--text-weight-semibold);cursor:pointer}.steps :deep(button:disabled){cursor:not-allowed;opacity:.55}</style>
<style scoped>
.onboarding .app-button { border-radius:var(--radius-control); padding:var(--space-1) var(--space-3); background:var(--control-bg); color:var(--control-ink); }
.onboarding .app-button--primary { border-color:var(--accent); background:var(--accent); color:var(--canvas); }
</style>
