<script setup lang="ts">
import {onMounted, ref} from "vue"
import type {CircleContactDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import AppStatus from "../components/AppStatus.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
import FriendlyCollectionHeader from "../components/FriendlyCollectionHeader.vue"
import FriendlySummaryCard from "../components/FriendlySummaryCard.vue"
import ModuleTabs from "../components/ModuleTabs.vue"
const tabs = [{id: "overview", label: "Your people", route: "/people", backendScope: "people.overview", emptyState: "Find someone you know."}, {id: "find", label: "Find people", route: "/people/find", backendScope: "people.find", emptyState: "Search for someone you trust."}, {id: "circles", label: "Circles", route: "/people/circles", backendScope: "people.circles", emptyState: "Create your first circle."}, {id: "requests", label: "Requests", route: "/people/requests", backendScope: "people.requests", emptyState: "No connection requests need attention."}, {id: "settings", label: "Settings", route: "/people/settings", backendScope: "people.settings", emptyState: "No additional settings are available."}]
const people = ref<CircleContactDTO[]>([])
const isLoading = ref(true)
const error = ref("")
const load = async () => { isLoading.value = true; error.value = ""; try { people.value = (await userShellApi.getCircleConnections()).items } catch { error.value = "Could not load your connections." } finally { isLoading.value = false } }
onMounted(() => void load())
</script>
<template><section class="people-overview" aria-label="People overview" data-people-overview="true" data-mental-model="connections-decisions-circles"><ModuleTabs :tabs="tabs" active-id="overview" /><FriendlyCollectionHeader eyebrow="People" title="Your people" description="Your accepted connections. Review invitations and manage sharing circles separately." tone="people" :primary-action="{label: 'Find people', to: '/people/find'}" /><nav class="people-overview__actions" aria-label="People actions"><FriendlySummaryCard title="Review requests" description="Decide connection invitations." icon="◌" tone="people" to="/people/requests" action-label="Review" /><FriendlySummaryCard title="Manage circles" description="Choose who shares a trusted space." icon="◎" tone="people" to="/people/circles" action-label="Open circles" /><FriendlySummaryCard title="People settings" description="Control sharing defaults." icon="⚙" tone="people" to="/people/settings" action-label="Settings" /></nav><AppStatus v-if="isLoading" message="Loading your people." busy /><AppStatus v-else-if="error" :message="error" tone="error" retry @retry="load" /><AppStatus v-else-if="!people.length" message="You have no connections yet. Find someone you know to get started." /><section v-else class="people-overview__list" aria-label="Connected people"><SurfaceRow v-for="person in people" :key="person.userId" :row="{id: String(person.userId), title: person.username, description: person.circleSummaryLabel || person.profileDescription || 'Connected person', badge: 'Connected', to: `/people/${person.userId}`}" /></section></section></template>
<style scoped>.people-overview{display:grid;gap:var(--space-4);min-width:0}.people-overview__actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--space-2)}.people-overview__list{display:grid;gap:var(--space-2)}.people-overview__list :deep(.surface-row){border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface-raised)}@media(max-width:760px){.people-overview__actions{grid-template-columns:1fr}}</style>
