<script setup lang="ts">
import {computed, onMounted, ref, watch} from "vue"
import type {RideOfferRequestDTO, RideOfferResponseDTO} from "../../../contracts/index.ts"
import {ridesApi, type CommutePreference} from "../../rides/api/ridesApi.ts"
import {useRoute, useRouter} from "vue-router"
import AppDialog from "../components/AppDialog.vue"
import AppButton from "../components/AppButton.vue"
import AppFormField from "../components/AppFormField.vue"
import AppFormFooter from "../components/AppFormFooter.vue"
import AppStatus from "../components/AppStatus.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
import ObjectPreviewPanel from "../components/ObjectPreviewPanel.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
import {useSurfaceViewState} from "../composables/useSurfaceViewState.ts"
import {useAsyncAction} from "../composables/useAsyncAction.ts"
import {currentUser} from "../../identity/auth.ts"
// Ride creation uses the shared backend guided-intake contract; matching remains a direct search interaction.
import GuidedIntakePanel from "../components/GuidedIntakePanel.vue"

const route = useRoute()
const router = useRouter()
const userShellApi = {joinRide: ridesApi.join, leaveRide: ridesApi.leave, startRide: ridesApi.start, completeRide: ridesApi.complete, cancelRide: ridesApi.cancel}
const mine = computed(() => route.path.endsWith("/mine"))
const rides = ref<RideOfferResponseDTO[]>([])
const form = ref<RideOfferRequestDTO | null>(null)
const guidedRideDraft = ref<Record<string, string> | null>(null)
const acceptGuidedRideDraft = (draft: Record<string, string>) => { guidedRideDraft.value = draft; form.value = {...blank(), origin: draft.origin ?? "", destination: draft.destination ?? "", departureAt: draft.departureTime ?? blank().departureAt} }
const editingId = ref<number | null>(null)
const loading = ref(true); const error = ref(""); const feedback = ref("")
const {pending: saving, error: actionError, execute} = useAsyncAction()
const matchOrigin = ref(""); const matchDestination = ref(""); const matchFrom = ref(""); const matchTo = ref("")
const commute = ref<CommutePreference>({id: null, enabled: false, consentGranted: false, homeArea: "", workArea: "", weekdays: [1,2,3,4,5], departureTime: "07:30", returnTime: "17:00", updatedAt: null})
const commuteSaving = ref(false)
const {state: viewState} = useSurfaceViewState("rides-discovery", computed(() => currentUser.value?.id), computed(() => route.fullPath))
const previewRide = ref<RideOfferResponseDTO | null>(null)
const previewLoading = ref(false)
const openDetail = (ride: RideOfferResponseDTO) => router.push({path: `/rides/${ride.id}`, query: {returnTo: route.fullPath}})
const load = async () => { loading.value = true; error.value = ""; try { rides.value = (await ridesApi.getOffersForScope(mine.value ? "mine" : "discover")).items } catch { error.value = "Could not load rides." } finally { loading.value = false } }
const loadCommute = async () => { try { const value = await ridesApi.getCommutePreference(); commute.value = {...commute.value, ...value, weekdays: value.weekdays?.length ? value.weekdays : commute.value.weekdays, departureTime: value.departureTime || commute.value.departureTime, returnTime: value.returnTime || commute.value.returnTime, homeArea: value.homeArea || "", workArea: value.workArea || ""} } catch { /* optional preference read */ } }
const saveCommute = async () => { commuteSaving.value = true; error.value = ""; try { commute.value = await ridesApi.updateCommutePreference({enabled: commute.value.enabled, consentGranted: commute.value.consentGranted, homeArea: commute.value.homeArea, workArea: commute.value.workArea, weekdays: commute.value.weekdays, departureTime: commute.value.departureTime, returnTime: commute.value.returnTime}); feedback.value = commute.value.enabled ? "Commute matching enabled." : "Commute matching paused." } catch { error.value = "Could not save commute preferences." } finally { commuteSaving.value = false } }
const findMatches = async () => { loading.value = true; error.value = ""; try { rides.value = (await ridesApi.findMatches({origin: matchOrigin.value, destination: matchDestination.value, departureFrom: matchFrom.value ? new Date(matchFrom.value).toISOString() : undefined, departureTo: matchTo.value ? new Date(matchTo.value).toISOString() : undefined})).items; feedback.value = "Showing rides matching your route and time." } catch { error.value = "Could not find matching rides." } finally { loading.value = false } }
const blank = (): RideOfferRequestDTO => ({origin: "", destination: "", departureAt: new Date(Date.now() + 86400000).toISOString().slice(0, 16), seats: 1, note: "", active: true, visibleCircleIds: []})
const create = async () => { if (!form.value) return; await execute(async () => { await ridesApi.createOffer({...form.value!, departureAt: new Date(form.value!.departureAt).toISOString()}); form.value = null; feedback.value = "Ride offered."; await load() }, "Could not offer this ride.") }
const edit = (ride: RideOfferResponseDTO) => { editingId.value = ride.id; form.value = {origin: ride.origin, destination: ride.destination, departureAt: new Date(ride.departureAt).toISOString().slice(0, 16), seats: ride.seats, note: ride.note || "", active: ride.active, visibleCircleIds: []} }
const save = async () => { if (!form.value || editingId.value === null) return; await execute(async () => { await ridesApi.updateOffer(editingId.value!, {...form.value!, departureAt: new Date(form.value!.departureAt).toISOString()}); form.value = null; editingId.value = null; feedback.value = "Ride updated."; await load() }, "Could not update this ride.") }
const action = async (label: string, fn: () => Promise<RideOfferResponseDTO>) => { await execute(async () => { await fn(); feedback.value = label; await load() }, "Could not update this ride.") }
const openPreview = async (ride: RideOfferResponseDTO) => { viewState.value.selectedId = ride.id; viewState.value.previewId = ride.id; previewRide.value = ride; previewLoading.value = true; try { previewRide.value = await ridesApi.getOffer(ride.id) } catch { error.value = "Could not load this ride preview."; viewState.value.previewId = null } finally { previewLoading.value = false } }
watch(() => route.query.create, (value) => { if (value === "1" && !form.value) form.value = blank() }, {immediate: true})
onMounted(() => { void load(); void loadCommute() })
</script>

<template>
  <section class="rides-surface">
    <header><div><p class="eyebrow">Rides</p><h1>{{ mine ? "My rides" : "Find a ride" }}</h1><p class="intro">Voluntary ride coordination for people in permitted circles. No continuous location tracking.</p></div><div class="actions"><AppButton :tone="!mine ? 'primary' : 'secondary'" @click="$router.push('/rides')">Discover</AppButton><AppButton :tone="mine ? 'primary' : 'secondary'" @click="$router.push('/rides/mine')">My rides</AppButton><AppButton tone="primary" @click="form = blank()">Offer a ride</AppButton></div></header>
    <form v-if="!mine" class="match-form" @submit.prevent="findMatches"><AppFormField label="From" required><input v-model="matchOrigin" placeholder="Origin area" aria-label="Match origin" required></AppFormField><AppFormField label="To" required><input v-model="matchDestination" placeholder="Destination area" aria-label="Match destination" required></AppFormField><AppFormField label="Earliest departure"><input v-model="matchFrom" type="datetime-local" aria-label="Earliest departure"></AppFormField><AppFormField label="Latest departure"><input v-model="matchTo" type="datetime-local" aria-label="Latest departure"></AppFormField><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" @click="load">Clear</AppButton></template><template #primary><AppButton type="submit" tone="primary">Find matching rides</AppButton></template></AppFormFooter></form>
    <form class="commute-form" @submit.prevent="saveCommute"><CollectionToolbar title="Commute matching"><template #actions><label class="check"><input v-model="commute.enabled" type="checkbox"> Suggest compatible rides</label></template></CollectionToolbar><p class="commute-form__privacy">Use approximate areas only. The backend does not accept exact addresses or continuous location tracking for this feature.</p><details class="commute-form__details"><summary>{{ commute.enabled ? "Edit commute preferences" : "Set up commute matching" }}</summary><div class="commute-form__fields"><AppFormField label="Approximate home area" hint="Area, not exact address."><input v-model="commute.homeArea" maxlength="160" placeholder="Area, not exact address"></AppFormField><AppFormField label="Approximate work area" hint="Area, not exact address."><input v-model="commute.workArea" maxlength="160" placeholder="Area, not exact address"></AppFormField><AppFormField label="Departure"><input v-model="commute.departureTime" type="time"></AppFormField><AppFormField label="Return" hint="Must be after departure when provided."><input v-model="commute.returnTime" type="time"></AppFormField></div><label class="check"><input v-model="commute.consentGranted" type="checkbox"> I consent to privacy-safe commute matching</label><AppFormFooter><template #primary><AppButton type="submit" tone="primary" :loading="commuteSaving">{{ commuteSaving ? "Saving" : "Save commute preferences" }}</AppButton></template></AppFormFooter></details></form>
    <AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error || actionError" :message="error || actionError" tone="error" retry @retry="load" />
    <AppStatus v-if="loading" message="Loading rides." /><AppStatus v-else-if="rides.length === 0" message="No rides available yet." />
    <div v-else class="ride-workspace"><div class="ride-grid"><SurfaceRow v-for="ride in rides" :key="ride.id" :row="{id: String(ride.id), title: `${ride.origin} → ${ride.destination}`, description: `${new Date(ride.departureAt).toLocaleString()} · ${ride.joinedSeats}/${ride.seats} seats`, meta: `Driver: ${ride.driverUsername}${ride.visibleCircleNames.length ? ` · ${ride.visibleCircleNames.join(', ')}` : ''}`, badge: ride.status}" :selected="viewState.selectedId === ride.id" :previewed="previewRide?.id === ride.id" @click="viewState.selectedId = ride.id" @preview="openPreview(ride)"><template #actions><div class="card-actions"><AppButton type="button" tone="quiet" @click.stop="openPreview(ride)">Preview</AppButton><AppButton v-if="ride.allowedActions.includes('EDIT')" type="button" tone="secondary" :loading="saving" @click="edit(ride)">Edit</AppButton><AppButton v-if="ride.allowedActions.includes('JOIN')" type="button" tone="primary" :loading="saving" @click="action('Joined ride.', () => userShellApi.joinRide(ride.id))">Join</AppButton><AppButton v-if="ride.allowedActions.includes('LEAVE')" type="button" tone="secondary" :loading="saving" @click="action('Left ride.', () => userShellApi.leaveRide(ride.id))">Leave</AppButton><AppButton v-if="ride.allowedActions.includes('START')" type="button" tone="primary" :loading="saving" @click="action('Ride started.', () => userShellApi.startRide(ride.id))">Start</AppButton><AppButton v-if="ride.allowedActions.includes('COMPLETE')" type="button" tone="primary" :loading="saving" @click="action('Ride completed.', () => userShellApi.completeRide(ride.id))">Complete</AppButton><AppButton v-if="ride.allowedActions.includes('CANCEL')" type="button" tone="danger" :loading="saving" @click="action('Ride cancelled.', () => userShellApi.cancelRide(ride.id))">Cancel</AppButton></div></template></SurfaceRow></div><ObjectPreviewPanel :title="previewRide ? `${previewRide.origin} → ${previewRide.destination}` : 'Ride'" subtitle="Ride preview" :open="viewState.previewId !== null" :loading="previewLoading" @close="viewState.previewId = null; previewRide = null" @open-detail="previewRide && openDetail(previewRide)"><p v-if="previewRide">{{ new Date(previewRide.departureAt).toLocaleString() }} · {{ previewRide.joinedSeats }}/{{ previewRide.seats }} seats</p><p v-if="previewRide">Driver: {{ previewRide.driverUsername }}</p><p v-if="previewRide?.note">{{ previewRide.note }}</p></ObjectPreviewPanel></div>
    <AppDialog :open="form !== null" :title="editingId === null ? 'Offer a ride' : 'Edit ride'" @close="form = null; editingId = null; guidedRideDraft = null"><GuidedIntakePanel v-if="editingId === null && !guidedRideDraft" flow="rides.offer.create" title="Offer a ride" @completed="acceptGuidedRideDraft" @cancel="form = null; guidedRideDraft = null" /><form v-else class="form" @submit.prevent="editingId === null ? create() : save()"><AppFormField label="From" required><input v-model="form!.origin" required maxlength="140"></AppFormField><AppFormField label="To" required><input v-model="form!.destination" required maxlength="140"></AppFormField><AppFormField label="Departure" required><input v-model="form!.departureAt" type="datetime-local" required></AppFormField><AppFormField label="Passenger seats" hint="The server enforces seat and ride-state limits." required><input v-model.number="form!.seats" type="number" min="1" max="8" required></AppFormField><AppFormField label="Note" optional><textarea v-model="form!.note" maxlength="1000" placeholder="Optional context for passengers."></textarea></AppFormField><p class="privacy">Visibility is circle-scoped when circles are selected. Exact address and continuous tracking are not part of rides.</p><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" @click="form = null; editingId = null; guidedRideDraft = null">Cancel</AppButton></template><template #primary><AppButton type="submit" tone="primary" :loading="saving">{{ saving ? "Saving" : (editingId === null ? "Offer ride" : "Save changes") }}</AppButton></template></AppFormFooter></form></AppDialog>
  </section>
</template>

<style scoped>
.rides-surface{display:grid;gap:var(--space-3);max-width:none}.rides-surface header{display:flex;justify-content:space-between;align-items:end;gap:var(--space-3)}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1{margin:0;font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}.intro{max-width:42rem;color:var(--text-muted)}.actions,.card-actions{display:flex;gap:var(--space-1);flex-wrap:wrap}.rides-surface button{border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit;cursor:pointer}.rides-surface button:hover{border-color:var(--control-border-active);background:var(--control-bg-hover)}.rides-surface button.active,.rides-surface button.primary{border-color:var(--accent);background:var(--accent);color:var(--canvas)}.ride-workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(18rem,var(--detail-rail-width));overflow:hidden;border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.ride-grid{display:grid}.ride-card{display:flex;justify-content:space-between;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.route{font-size:var(--text-size-title);font-weight:var(--text-weight-semibold);margin:0}.meta,small{color:var(--text-muted)}.status{padding:var(--space-2) 0;color:var(--text-muted)}.success{color:var(--success)}.error{color:var(--danger)}.status button{border:0;text-decoration:underline;padding:0;background:transparent}.form{display:grid;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.form label{display:grid;gap:var(--space-1);font-weight:var(--text-weight-semibold)}.form input,.form textarea{border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.form textarea{min-height:5rem}.privacy{font-size:var(--text-size-meta);color:var(--text-muted)}@media(max-width:980px){.ride-workspace{grid-template-columns:1fr}}@media(max-width:650px){.rides-surface header,.ride-card{align-items:start;flex-direction:column}}
.match-form{display:grid;grid-template-columns:repeat(4,1fr) auto auto;gap:var(--space-2);align-items:center;padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.match-form input{min-width:0;border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.commute-form{display:grid;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.commute-form__privacy{margin:0;color:var(--text-muted);font-size:var(--text-size-body);line-height:1.45}.commute-form__fields{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space-2)}.commute-form :deep(input:not([type=checkbox])){width:100%;min-width:0;border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.commute-form .check{display:flex;align-items:center;gap:var(--space-1);min-height:var(--control-height-default);font-size:var(--text-size-body);font-weight:var(--text-weight-semibold)}.commute-form .check input{width:auto}@media(max-width:850px){.match-form,.commute-form__fields{grid-template-columns:1fr 1fr}.match-form button,.commute-form button{justify-self:start}}@media(max-width:560px){.commute-form__fields{grid-template-columns:1fr}}
.rides-surface{gap:var(--space-3)}.rides-surface h1{font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}.rides-surface button{min-height:var(--control-height-default);border-radius:var(--radius-control);background:var(--control-bg);color:var(--control-ink)}.rides-surface button.active,.rides-surface button.primary{border-color:var(--accent);background:var(--accent);color:var(--canvas)}.ride-card,.form{border-radius:var(--radius-surface);background:var(--surface-base);padding:var(--space-3)}.form input,.form textarea,.match-form input{border-radius:var(--radius-control);padding:var(--space-2);background:var(--control-bg);color:var(--control-ink)}
</style>
<style scoped>
.rides-surface .app-button { border-radius:var(--radius-control); padding:var(--space-1) var(--space-3); background:var(--control-bg); color:var(--control-ink); }
.rides-surface .app-button--primary { border-color:var(--accent); background:var(--accent); color:var(--canvas); }
.rides-surface .app-button--danger { color:var(--danger); }
.match-form { padding: var(--space-3); border: 1px solid var(--border-subtle); border-radius: var(--radius-surface); background: var(--surface-base); }
.ride-workspace { background: var(--surface-base); }
</style>
<style scoped>
/* Rides keeps privacy-sensitive matching compact while reusing the workspace control contract. */
.match-form { gap: var(--space-2); }
.match-form input { border-color: var(--control-border); background: var(--control-bg); color: var(--control-ink); }
.ride-workspace { background: var(--surface-base); }
.rides-surface button:hover { border-color: var(--border-strong); background: var(--surface-hover); }
.rides-surface button.active:hover,
.rides-surface button.primary:hover { border-color: var(--accent); background: var(--accent-hover, var(--accent)); color: var(--canvas); }
.commute-form :deep(input:not([type=checkbox])):focus-visible,
.match-form input:focus-visible { border-color: var(--accent); outline: 2px solid color-mix(in srgb, var(--accent) 35%, transparent); outline-offset: 1px; }
</style>
