<script setup lang="ts">
import {computed, onMounted, ref, watch} from "vue"
import type {CircleGroupResponseDTO, RideOfferRequestDTO, RideOfferResponseDTO} from "../../../contracts/index.ts"
import {ridesApi, type CommutePreference} from "../../rides/api/ridesApi.ts"
import {userShellApi as shellApi} from "../api/userShellApi.ts"
import {useRoute} from "vue-router"
import AppDialog from "../components/AppDialog.vue"
import AppButton from "../components/AppButton.vue"
import AppFormField from "../components/AppFormField.vue"
import AppFormFooter from "../components/AppFormFooter.vue"
import AppStatus from "../components/AppStatus.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
import {collectionReturnQuery} from "../composables/useSurfaceViewState.ts"
import {useAsyncAction} from "../composables/useAsyncAction.ts"
import {formatDateTime} from "../../../services/formatters.ts"
// Ride creation uses the shared backend guided-intake contract; matching remains a direct search interaction.
import GuidedIntakePanel from "../components/GuidedIntakePanel.vue"
import FriendlyCollectionHeader from "../components/FriendlyCollectionHeader.vue"
import FriendlySummaryCard from "../components/FriendlySummaryCard.vue"
import ModuleTabs from "../components/ModuleTabs.vue"
import ClientActionList from "../components/ClientActionList.vue"

const route = useRoute()
const userShellApi = {getSuggestions: ridesApi.getSuggestions, joinRide: ridesApi.join, leaveRide: ridesApi.leave, startRide: ridesApi.start, completeRide: ridesApi.complete, cancelRide: ridesApi.cancel}
const circleGroups = ref<CircleGroupResponseDTO[]>([])
const mine = computed(() => route.path.endsWith("/mine"))
const tabs = [{id: "find", label: "Find a ride", route: "/rides", backendScope: "rides.find", emptyState: "No rides match your route yet."}, {id: "mine", label: "My rides", route: "/rides/mine", backendScope: "rides.mine", emptyState: "You have no active rides yet."}]
const rides = ref<RideOfferResponseDTO[]>([])
const form = ref<RideOfferRequestDTO | null>(null)
const guidedRideDraft = ref<Record<string, string> | null>(null)
const acceptGuidedRideDraft = (draft: Record<string, string>) => { guidedRideDraft.value = draft; form.value = {...blank(), origin: draft.origin ?? "", destination: draft.destination ?? "", departureAt: draft.departureTime ?? blank().departureAt} }
const editingId = ref<number | null>(null)
const loading = ref(true); const error = ref(""); const feedback = ref("")
const {pending: saving, error: actionError, execute} = useAsyncAction()
const matchOrigin = ref(""); const matchDestination = ref(""); const matchFrom = ref(""); const matchTo = ref("")
const commute = ref<CommutePreference>({id: null, enabled: false, consentGranted: false, homeArea: "", workArea: "", weekdays: [1,2,3,4,5], departureTime: "07:30", returnTime: "17:00", updatedAt: null})
const commuteSaving = ref(false)
const weekdays = [{value: 1, label: "Mon"}, {value: 2, label: "Tue"}, {value: 3, label: "Wed"}, {value: 4, label: "Thu"}, {value: 5, label: "Fri"}, {value: 6, label: "Sat"}, {value: 7, label: "Sun"}]
const pageTitle = computed(() => mine.value ? "My rides" : "Find a ride")
const pageDescription = computed(() => mine.value
  ? "Manage rides you offered or joined, and complete each journey when it is finished."
  : "Find a ride that fits your route. You choose whether to join.")
const load = async () => { loading.value = true; error.value = ""; try { rides.value = (mine.value ? await ridesApi.getOffersForScope("mine") : await userShellApi.getSuggestions()).items } catch { error.value = "Could not load rides." } finally { loading.value = false } }
const loadCommute = async () => { try { const value = await ridesApi.getCommutePreference(); commute.value = {...commute.value, ...value, weekdays: value.weekdays?.length ? value.weekdays : commute.value.weekdays, departureTime: value.departureTime || commute.value.departureTime, returnTime: value.returnTime || commute.value.returnTime, homeArea: value.homeArea || "", workArea: value.workArea || ""} } catch { /* optional preference read */ } }
const loadCircleGroups = async () => { try { circleGroups.value = await shellApi.getCircleGroups() } catch { circleGroups.value = [] } }
const saveCommute = async () => { commuteSaving.value = true; error.value = ""; try { commute.value = await ridesApi.updateCommutePreference({enabled: commute.value.enabled, consentGranted: commute.value.consentGranted, homeArea: commute.value.homeArea, workArea: commute.value.workArea, weekdays: commute.value.weekdays, departureTime: commute.value.departureTime, returnTime: commute.value.returnTime}); feedback.value = commute.value.enabled ? "Commute matching enabled." : "Commute matching paused." } catch { error.value = "Could not save commute preferences." } finally { commuteSaving.value = false } }
const findMatches = async () => { loading.value = true; error.value = ""; try { rides.value = (await ridesApi.findMatches({origin: matchOrigin.value, destination: matchDestination.value, departureFrom: matchFrom.value ? new Date(matchFrom.value).toISOString() : undefined, departureTo: matchTo.value ? new Date(matchTo.value).toISOString() : undefined})).items; feedback.value = "Showing rides matching your route and time." } catch { error.value = "Could not find matching rides." } finally { loading.value = false } }
const blank = (): RideOfferRequestDTO => ({origin: "", destination: "", departureAt: new Date(Date.now() + 86400000).toISOString().slice(0, 16), seats: 1, note: "", active: true, visibleCircleIds: []})
const create = async () => { if (!form.value) return; await execute(async () => { await ridesApi.createOffer({...form.value!, departureAt: new Date(form.value!.departureAt).toISOString()}); form.value = null; feedback.value = "Ride offered."; await load() }, "Could not offer this ride.") }
const edit = (ride: RideOfferResponseDTO) => { editingId.value = ride.id; form.value = {origin: ride.origin, destination: ride.destination, departureAt: new Date(ride.departureAt).toISOString().slice(0, 16), seats: ride.seats, note: ride.note || "", active: ride.active, visibleCircleIds: ride.visibleCircleIds || []} }
const save = async () => { if (!form.value || editingId.value === null) return; await execute(async () => { await ridesApi.updateOffer(editingId.value!, {...form.value!, departureAt: new Date(form.value!.departureAt).toISOString()}); form.value = null; editingId.value = null; feedback.value = "Ride updated."; await load() }, "Could not update this ride.") }
const action = async (label: string, fn: () => Promise<RideOfferResponseDTO>) => { await execute(async () => { await fn(); feedback.value = label; await load() }, "Could not update this ride.") }
const executeClientAction = (ride: RideOfferResponseDTO, actionId: string) => {
  if (actionId === "EDIT") return edit(ride)
  const handler = ({JOIN: () => userShellApi.joinRide(ride.id), LEAVE: () => userShellApi.leaveRide(ride.id), START: () => userShellApi.startRide(ride.id), COMPLETE: () => userShellApi.completeRide(ride.id), CANCEL: () => userShellApi.cancelRide(ride.id)} as Record<string, (() => Promise<RideOfferResponseDTO>) | undefined>)[actionId]
  const descriptor = ride.actions.find(item => item.id === actionId)
  if (handler) void action(descriptor?.outcome ?? "Ride updated.", handler)
}
watch(() => route.query.create, (value) => { if (value === "1" && !form.value) form.value = blank() }, {immediate: true})
onMounted(() => { void load(); void loadCommute(); void loadCircleGroups() })
</script>

<template>
  <section class="rides-surface" data-collection-rhythm="oriented" :data-mental-model="mine ? 'manage-open-complete' : 'find-optional-match-open-join'">
    <ModuleTabs :tabs="tabs" :active-id="mine ? 'mine' : 'find'" />
    <FriendlyCollectionHeader eyebrow="Rides" :title="pageTitle" :description="pageDescription" tone="ride" :primary-action="mine ? {label: 'Find a ride', to: '/rides'} : {label: 'Offer a ride', to: {path: '/rides', query: {create: '1'}}}" />
    <FriendlySummaryCard v-if="!mine" eyebrow="One-time ride" title="Where do you need to go?" description="Search a route and choose a ride only when it suits you. Regular commute matching stays optional." icon="↗" tone="ride" />
    <form v-if="!mine" class="match-form" @submit.prevent="findMatches"><AppFormField label="Leaving from" required><input v-model="matchOrigin" placeholder="Area or town" aria-label="Match origin" required></AppFormField><AppFormField label="Going to" required><input v-model="matchDestination" placeholder="Area or town" aria-label="Match destination" required></AppFormField><AppFormField label="Earliest departure" optional><input v-model="matchFrom" type="datetime-local" aria-label="Earliest departure"></AppFormField><AppFormField label="Latest departure" optional><input v-model="matchTo" type="datetime-local" aria-label="Latest departure"></AppFormField><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" @click="load">Show suggested rides</AppButton></template><template #primary><AppButton type="submit" tone="primary">Find rides for this route</AppButton></template></AppFormFooter></form>
    <details v-if="!mine" class="commute-setup" data-commute-setup="opt-in"><summary><span><strong>{{ commute.enabled ? "Regular commute matching is on" : "Set up regular commute matching" }}</strong><small>{{ commute.enabled ? "Review or pause your saved preferences." : "Optional: receive suggestions for a repeating route." }}</small></span></summary><form class="commute-form" @submit.prevent="saveCommute"><CollectionToolbar title="Regular commute matching"><template #actions><label class="check"><input v-model="commute.enabled" type="checkbox"> Suggest compatible rides</label></template></CollectionToolbar><p class="commute-form__privacy">Use approximate areas only. The backend does not accept exact addresses or continuous location tracking for this feature.</p><div class="commute-form__fields"><AppFormField label="Approximate home area" hint="Area, not exact address."><input v-model="commute.homeArea" maxlength="160" placeholder="Area, not exact address"></AppFormField><AppFormField label="Approximate work area" hint="Area, not exact address."><input v-model="commute.workArea" maxlength="160" placeholder="Area, not exact address"></AppFormField><AppFormField label="Departure"><input v-model="commute.departureTime" type="time"></AppFormField><AppFormField label="Return" hint="Must be after departure when provided."><input v-model="commute.returnTime" type="time"></AppFormField></div><fieldset class="commute-weekdays"><legend>Usual days</legend><label v-for="day in weekdays" :key="day.value" class="check"><input v-model="commute.weekdays" type="checkbox" :value="day.value"> {{ day.label }}</label></fieldset><label class="check"><input v-model="commute.consentGranted" type="checkbox"> I consent to privacy-safe commute matching</label><AppFormFooter><template #primary><AppButton type="submit" tone="primary" :loading="commuteSaving">{{ commuteSaving ? "Saving" : "Save commute preferences" }}</AppButton></template></AppFormFooter></form></details>
    <AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error || actionError" :message="error || actionError" tone="error" retry @retry="load" /><p v-if="!mine && rides.length" class="rides-suggestion-note" data-suggestion-explanation="backend-ranked">Suggestions use your consented commute areas, schedule, and circle visibility.</p>
    <AppStatus v-if="loading" message="Loading rides." busy /><AppStatus v-else-if="rides.length === 0" :message="mine ? 'You have no active rides yet.' : 'No rides match your route yet.'" />
    <div v-else class="ride-workspace"><div class="ride-grid"><SurfaceRow v-for="ride in rides" :key="ride.id" :row="{id: String(ride.id), title: `${ride.origin} → ${ride.destination}`, description: `${formatDateTime(ride.departureAt, 'Unknown time')} · ${ride.joinedSeats}/${ride.seats} seats`, meta: `Driver: ${ride.driverUsername}${ride.visibleCircleNames.length ? ` · ${ride.visibleCircleNames.join(', ')}` : ''}`, badge: ride.status, to: {path: `/rides/${ride.id}`, query: collectionReturnQuery(route.fullPath)}}"><template #actions><ClientActionList :actions="ride.actions" :busy="saving" @execute="executeClientAction(ride, $event)" /></template></SurfaceRow></div></div>
    <AppDialog :open="form !== null" :title="editingId === null ? 'Offer a ride' : 'Edit ride'" @close="form = null; editingId = null; guidedRideDraft = null"><GuidedIntakePanel v-if="editingId === null && !guidedRideDraft" flow="rides.offer.create" title="Offer a ride" @completed="acceptGuidedRideDraft" @cancel="form = null; guidedRideDraft = null" /><form v-else class="form" @submit.prevent="editingId === null ? create() : save()"><AppFormField label="From" required><input v-model="form!.origin" required maxlength="140"></AppFormField><AppFormField label="To" required><input v-model="form!.destination" required maxlength="140"></AppFormField><AppFormField label="Departure" required><input v-model="form!.departureAt" type="datetime-local" required></AppFormField><AppFormField label="Passenger seats" hint="The server enforces seat and ride-state limits." required><input v-model.number="form!.seats" type="number" min="1" max="8" required></AppFormField><AppFormField label="Note" optional><textarea v-model="form!.note" maxlength="1000" placeholder="Optional context for passengers."></textarea></AppFormField><label class="check"><input v-model="form!.active" type="checkbox"> Offer is active</label><fieldset v-if="circleGroups.length" class="ride-visibility"><legend>Visible circles</legend><label v-for="group in circleGroups" :key="group.id" class="check"><input v-model="form!.visibleCircleIds" type="checkbox" :value="group.id"> {{ group.name }}</label></fieldset><p class="privacy">Visibility is circle-scoped when circles are selected. Exact address and continuous tracking are not part of rides.</p><AppFormFooter><template #secondary><AppButton type="button" tone="secondary" @click="form = null; editingId = null; guidedRideDraft = null">Cancel</AppButton></template><template #primary><AppButton type="submit" tone="primary" :loading="saving">{{ saving ? "Saving" : (editingId === null ? "Offer ride" : "Save changes") }}</AppButton></template></AppFormFooter></form></AppDialog>
  </section>
</template>

<style scoped>
.rides-surface{display:grid;gap:var(--space-3);max-width:none}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h2{margin:var(--space-1) 0;font-size:var(--text-size-title)}.intro{max-width:42rem;color:var(--text-muted)}.actions,.card-actions{display:flex;gap:var(--space-1);flex-wrap:wrap}.rides-surface button{border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit;cursor:pointer}.rides-surface button:hover{border-color:var(--control-border-active);background:var(--control-bg-hover)}.rides-surface button.active,.rides-surface button.primary{border-color:var(--accent);background:var(--accent);color:var(--canvas)}.ride-workspace{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-3);overflow:visible;border:0;border-radius:0;background:transparent}.ride-grid{display:grid;gap:var(--space-2)}.ride-grid :deep(.surface-row){border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface-raised)}.ride-grid :deep(.surface-row:hover){background:var(--surface-hover);transform:translateY(-1px)}.ride-card{display:flex;justify-content:space-between;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.route{font-size:var(--text-size-title);font-weight:var(--text-weight-semibold);margin:0}.meta,small{color:var(--text-muted)}.status{padding:var(--space-2) 0;color:var(--text-muted)}.success{color:var(--success)}.error{color:var(--danger)}.status button{border:0;text-decoration:underline;padding:0;background:transparent}.form{display:grid;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.form label{display:grid;gap:var(--space-1);font-weight:var(--text-weight-semibold)}.form input,.form textarea{border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.form textarea{min-height:5rem}.privacy{font-size:var(--text-size-meta);color:var(--text-muted)}@media(max-width:650px){.ride-card{align-items:start;flex-direction:column}}
.match-form{display:grid;grid-template-columns:repeat(4,1fr) auto auto;gap:var(--space-2);align-items:center;padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.match-form input{min-width:0;border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.commute-setup{border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.commute-setup summary{display:flex;min-height:4rem;align-items:center;padding:var(--space-3);cursor:pointer;list-style:none}.commute-setup summary::-webkit-details-marker{display:none}.commute-setup summary span{display:grid;gap:var(--space-1)}.commute-setup summary strong{color:var(--text)}.commute-setup summary small{color:var(--text-muted)}.commute-form{display:grid;gap:var(--space-3);padding:0 var(--space-3) var(--space-3)}.commute-form__privacy{margin:0;color:var(--text-muted);font-size:var(--text-size-body);line-height:1.45}.commute-form__fields{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space-2)}.commute-form :deep(input:not([type=checkbox])){width:100%;min-width:0;border:1px solid var(--control-border);border-radius:var(--radius-control);padding:var(--space-1) var(--space-2);background:var(--control-bg);color:var(--control-ink);font:inherit}.commute-form .check{display:flex;align-items:center;gap:var(--space-1);min-height:var(--control-height-default);font-size:var(--text-size-body);font-weight:var(--text-weight-semibold)}.commute-form .check input{width:auto}@media(max-width:850px){.match-form,.commute-form__fields{grid-template-columns:1fr 1fr}.match-form button,.commute-form button{justify-self:start}}@media(max-width:560px){.commute-form__fields{grid-template-columns:1fr}}
.rides-surface{gap:var(--space-3)}.rides-surface h1{font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}.rides-surface button{min-height:var(--control-height-default);border-radius:var(--radius-control);background:var(--control-bg);color:var(--control-ink)}.rides-surface button.active,.rides-surface button.primary{border-color:var(--accent);background:var(--accent);color:var(--canvas)}.rides-surface .app-button{border-radius:var(--radius-control);padding:var(--space-1) var(--space-3);background:var(--control-bg);color:var(--control-ink)}.rides-surface .app-button--primary{border-color:var(--accent);background:var(--accent);color:var(--canvas)}.rides-surface .app-button--danger{color:var(--danger)}.rides-trust-summary{display:grid;gap:var(--space-1);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-raised);color:var(--text-muted)}.rides-trust-summary strong{color:var(--text)}.match-form{gap:var(--space-2);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.ride-workspace{background:var(--surface-base)}.match-form input{border-color:var(--control-border);background:var(--control-bg);color:var(--control-ink)}.rides-surface button:hover{border-color:var(--border-strong);background:var(--surface-hover)}.rides-surface button.active:hover,.rides-surface button.primary:hover{border-color:var(--accent);background:var(--accent-hover,var(--accent));color:var(--canvas)}.commute-form :deep(input:not([type=checkbox])):focus-visible,.match-form input:focus-visible{border-color:var(--accent);outline:2px solid color-mix(in srgb,var(--accent) 35%,transparent);outline-offset:1px}.ride-visibility{display:grid;gap:var(--space-1);margin:0;border:1px solid var(--border-subtle);border-radius:var(--radius-control);padding:var(--space-2)}.ride-visibility legend{padding:0 var(--space-1);font-weight:var(--text-weight-semibold)}
.commute-weekdays{display:flex;flex-wrap:wrap;gap:var(--space-2);margin:0;border:1px solid var(--border-subtle);border-radius:var(--radius-control);padding:var(--space-2)}.commute-weekdays legend{width:100%;padding:0 var(--space-1);font-weight:var(--text-weight-semibold)}.commute-weekdays .check{min-height:var(--control-height-compact);padding:0 var(--space-1)}</style>
