<script setup lang="ts">
import {computed, onMounted, ref, watch} from "vue"
import type {RideOfferRequestDTO, RideOfferResponseDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import type {CommutePreference} from "../api/userShellApi.ts"
import {useRoute} from "vue-router"
import AppDialog from "../components/AppDialog.vue"
import AppStatus from "../components/AppStatus.vue"
import SurfaceRow from "../components/SurfaceRow.vue"

const route = useRoute()
const mine = computed(() => route.path.endsWith("/mine"))
const rides = ref<RideOfferResponseDTO[]>([])
const form = ref<RideOfferRequestDTO | null>(null)
const editingId = ref<number | null>(null)
const loading = ref(true); const saving = ref(false); const error = ref(""); const feedback = ref("")
const matchOrigin = ref(""); const matchDestination = ref(""); const matchFrom = ref(""); const matchTo = ref("")
const commute = ref<CommutePreference>({id: null, enabled: false, consentGranted: false, homeArea: "", workArea: "", weekdays: [1,2,3,4,5], departureTime: "07:30", returnTime: "17:00", updatedAt: null})
const commuteSaving = ref(false)
const load = async () => { loading.value = true; error.value = ""; try { rides.value = (mine.value ? await userShellApi.getMyRideOffers() : await userShellApi.getRideOffers()).items } catch { error.value = "Could not load rides." } finally { loading.value = false } }
const loadCommute = async () => { try { const value = await userShellApi.getCommutePreference(); commute.value = {...commute.value, ...value, weekdays: value.weekdays?.length ? value.weekdays : commute.value.weekdays, departureTime: value.departureTime || commute.value.departureTime, returnTime: value.returnTime || commute.value.returnTime, homeArea: value.homeArea || "", workArea: value.workArea || ""} } catch { /* optional preference read */ } }
const saveCommute = async () => { commuteSaving.value = true; error.value = ""; try { commute.value = await userShellApi.updateCommutePreference({enabled: commute.value.enabled, consentGranted: commute.value.consentGranted, homeArea: commute.value.homeArea, workArea: commute.value.workArea, weekdays: commute.value.weekdays, departureTime: commute.value.departureTime, returnTime: commute.value.returnTime}); feedback.value = commute.value.enabled ? "Commute matching enabled." : "Commute matching paused." } catch { error.value = "Could not save commute preferences." } finally { commuteSaving.value = false } }
const findMatches = async () => { loading.value = true; error.value = ""; try { rides.value = (await userShellApi.findRideMatches({origin: matchOrigin.value, destination: matchDestination.value, departureFrom: matchFrom.value ? new Date(matchFrom.value).toISOString() : undefined, departureTo: matchTo.value ? new Date(matchTo.value).toISOString() : undefined})).items; feedback.value = "Showing rides matching your route and time." } catch { error.value = "Could not find matching rides." } finally { loading.value = false } }
const blank = (): RideOfferRequestDTO => ({origin: "", destination: "", departureAt: new Date(Date.now() + 86400000).toISOString().slice(0, 16), seats: 1, note: "", active: true, visibleCircleIds: []})
const create = async () => { if (!form.value) return; saving.value = true; error.value = ""; try { await userShellApi.createRideOffer({...form.value, departureAt: new Date(form.value.departureAt).toISOString()}); form.value = null; feedback.value = "Ride offered."; await load() } catch { error.value = "Could not offer this ride." } finally { saving.value = false } }
const edit = (ride: RideOfferResponseDTO) => { editingId.value = ride.id; form.value = {origin: ride.origin, destination: ride.destination, departureAt: new Date(ride.departureAt).toISOString().slice(0, 16), seats: ride.seats, note: ride.note || "", active: true, visibleCircleIds: []} }
const save = async () => { if (!form.value || editingId.value === null) return; saving.value = true; error.value = ""; try { await userShellApi.updateRideOffer(editingId.value, {...form.value, departureAt: new Date(form.value.departureAt).toISOString()}); form.value = null; editingId.value = null; feedback.value = "Ride updated."; await load() } catch { error.value = "Could not update this ride." } finally { saving.value = false } }
const action = async (label: string, fn: () => Promise<RideOfferResponseDTO>) => { saving.value = true; error.value = ""; try { await fn(); feedback.value = label; await load() } catch { error.value = "Could not update this ride." } finally { saving.value = false } }
watch(() => route.query.create, (value) => { if (value === "1" && !form.value) form.value = blank() }, {immediate: true})
onMounted(() => { void load(); void loadCommute() })
</script>

<template>
  <section class="rides-surface">
    <header><div><p class="eyebrow">Rides</p><h1>{{ mine ? "My rides" : "Find a ride" }}</h1><p class="intro">Voluntary ride coordination for people in permitted circles. No continuous location tracking.</p></div><div class="actions"><button :class="{active: !mine}" @click="$router.push('/rides')">Discover</button><button :class="{active: mine}" @click="$router.push('/rides/mine')">My rides</button><button class="primary" @click="form = blank()">Offer a ride</button></div></header>
    <form v-if="!mine" class="match-form" @submit.prevent="findMatches"><input v-model="matchOrigin" placeholder="From" aria-label="Match origin"><input v-model="matchDestination" placeholder="To" aria-label="Match destination"><input v-model="matchFrom" type="datetime-local" aria-label="Earliest departure"><input v-model="matchTo" type="datetime-local" aria-label="Latest departure"><button class="primary" type="submit">Find matching rides</button><button type="button" @click="load">Clear</button></form>
    <form class="commute-form" @submit.prevent="saveCommute"><strong>Commute matching</strong><label class="check"><input v-model="commute.enabled" type="checkbox"> Suggest compatible rides</label><label>Approximate home area<input v-model="commute.homeArea" maxlength="160" placeholder="Area, not exact address"></label><label>Approximate work area<input v-model="commute.workArea" maxlength="160" placeholder="Area, not exact address"></label><label>Departure<input v-model="commute.departureTime" type="time"></label><label>Return<input v-model="commute.returnTime" type="time"></label><label class="check"><input v-model="commute.consentGranted" type="checkbox"> I consent to privacy-safe commute matching</label><button class="primary" :disabled="commuteSaving" type="submit">{{ commuteSaving ? "Saving" : "Save commute preferences" }}</button></form>
    <AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error" :message="error" tone="error" retry @retry="load" />
    <AppStatus v-if="loading" message="Loading rides." /><AppStatus v-else-if="rides.length === 0" message="No rides available yet." />
    <div v-else class="ride-grid"><SurfaceRow v-for="ride in rides" :key="ride.id" :row="{title: `${ride.origin} → ${ride.destination}`, description: `${new Date(ride.departureAt).toLocaleString()} · ${ride.joinedSeats}/${ride.seats} seats`, meta: `Driver: ${ride.driverUsername}${ride.visibleCircleNames.length ? ` · ${ride.visibleCircleNames.join(', ')}` : ''}`, badge: ride.status}"><template #actions><div class="card-actions"><button v-if="ride.viewerIsDriver && ['OPEN','FULL'].includes(ride.status)" :disabled="saving" @click="edit(ride)">Edit</button><button v-if="ride.canJoin" :disabled="saving" @click="action('Joined ride.', () => userShellApi.joinRide(ride.id))">Join</button><button v-if="ride.canLeave" :disabled="saving" @click="action('Left ride.', () => userShellApi.leaveRide(ride.id))">Leave</button><button v-if="ride.viewerIsDriver && ride.status === 'FULL'" :disabled="saving" @click="action('Ride started.', () => userShellApi.startRide(ride.id))">Start</button><button v-if="ride.viewerIsDriver && ride.status === 'IN_PROGRESS'" :disabled="saving" @click="action('Ride completed.', () => userShellApi.completeRide(ride.id))">Complete</button><button v-if="ride.viewerIsDriver && ['OPEN','FULL'].includes(ride.status)" :disabled="saving" @click="action('Ride cancelled.', () => userShellApi.cancelRide(ride.id))">Cancel</button></div></template></SurfaceRow></div>
    <AppDialog :open="form !== null" :title="editingId === null ? 'Offer a ride' : 'Edit ride'" @close="form = null; editingId = null"><form class="form" @submit.prevent="editingId === null ? create() : save()"><label>From<input v-model="form!.origin" required maxlength="140"></label><label>To<input v-model="form!.destination" required maxlength="140"></label><label>Departure<input v-model="form!.departureAt" type="datetime-local" required></label><label>Passenger seats<input v-model.number="form!.seats" type="number" min="1" max="8" required></label><label>Note<textarea v-model="form!.note" maxlength="1000" placeholder="Optional context for passengers."></textarea></label><p class="privacy">Visibility is circle-scoped when circles are selected. Exact address and continuous tracking are not part of rides.</p><div><button class="primary" :disabled="saving">{{ saving ? "Saving" : (editingId === null ? "Offer ride" : "Save changes") }}</button><button type="button" @click="form = null; editingId = null">Cancel</button></div></form></AppDialog>
  </section>
</template>

<style scoped>
.rides-surface{display:grid;gap:1rem;max-width:62rem}.rides-surface header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.eyebrow{margin:0 0 .3rem;color:var(--text-muted);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem);letter-spacing:-.075em}.intro{max-width:42rem;color:var(--text-muted)}.actions,.card-actions{display:flex;gap:.35rem;flex-wrap:wrap}.rides-surface button{border:1px solid var(--border-subtle);border-radius:999px;padding:.5rem .75rem;background:transparent;font:inherit;cursor:pointer}.rides-surface button.active,.rides-surface button.primary{background:var(--accent);color:var(--text)}.ride-grid{display:grid;gap:.75rem}.ride-card{display:flex;justify-content:space-between;gap:1rem;padding:1rem;border:1px solid var(--border-subtle);border-radius:1rem;background:var(--surface)}.route{font-size:1.15rem;font-weight:700;margin:0}.meta,small{color:var(--text-muted)}.status{padding:.7rem 0;color:var(--text-muted)}.success{color:var(--success)}.error{color:var(--danger)}.status button{border:0;text-decoration:underline;padding:0}.form{display:grid;gap:.75rem;padding:1rem;border:1px solid var(--border-subtle)}.form label{display:grid;gap:.35rem;font-weight:650}.form input,.form textarea{border:1px solid var(--border-subtle);border-radius:.65rem;padding:.65rem;font:inherit}.form textarea{min-height:5rem}.privacy{font-size:.88rem;color:var(--text-muted)}@media(max-width:650px){.rides-surface header,.ride-card{align-items:start;flex-direction:column}}
.match-form{display:grid;grid-template-columns:repeat(4,1fr) auto auto;gap:.45rem;align-items:center}.match-form input{min-width:0;border:1px solid var(--border-subtle);border-radius:.65rem;padding:.55rem;font:inherit}.commute-form{display:grid;grid-template-columns:1.5fr repeat(4,1fr) 2fr auto;gap:.55rem;align-items:end;padding:.8rem;border:1px solid var(--border-subtle);border-radius:.9rem;background:var(--surface)}.commute-form label{display:grid;gap:.25rem;font-size:.76rem;font-weight:650}.commute-form input:not([type=checkbox]){min-width:0;border:1px solid var(--border-subtle);border-radius:.55rem;padding:.5rem;font:inherit}.commute-form .check{display:flex;align-items:center;gap:.35rem;height:2rem}.commute-form .check input{width:auto}@media(max-width:850px){.match-form,.commute-form{grid-template-columns:1fr 1fr}.match-form button,.commute-form button{justify-self:start}}
</style>
