<script setup lang="ts">
import {onMounted, ref} from "vue"
import {userShellApi, type SavedSearchIntent} from "../api/userShellApi.ts"
import AppStatus from "../components/AppStatus.vue"
import AppButton from "../components/AppButton.vue"
import CollectionToolbar from "../components/CollectionToolbar.vue"
import SurfaceRow from "../components/SurfaceRow.vue"
import {confirmAction} from "../composables/useActionDialog.ts"

const items = ref<SavedSearchIntent[]>([])
const loading = ref(true); const error = ref(""); const feedback = ref(""); const actingId = ref<number | null>(null)
const editingId = ref<number | null>(null); const editingQuery = ref("")
// Pause/delete are the only mutations exposed here; search execution remains a destination concern.
const load = async () => { loading.value = true; error.value = ""; try { items.value = await userShellApi.getSavedSearchIntents() } catch { error.value = "Could not load saved searches." } finally { loading.value = false } }
const toggle = async (item: SavedSearchIntent) => { actingId.value = item.id; try { const updated = await userShellApi.updateSavedSearchIntent(item.id, {query: item.query, entityFamily: item.entityFamily, paused: !item.paused, notifyEnabled: item.notifyEnabled, expiresAt: item.expiresAt}); items.value = items.value.map(current => current.id === updated.id ? updated : current); feedback.value = updated.paused ? "Search paused. You will not receive updates until you resume it." : "Search resumed. Matching updates can appear again." } catch { error.value = "Could not update this search." } finally { actingId.value = null } }
const remove = async (item: SavedSearchIntent) => { if (!await confirmAction("Deleting removes this saved search and its future updates.", "Delete saved search")) return; actingId.value = item.id; try { await userShellApi.deleteSavedSearchIntent(item.id); items.value = items.value.filter(current => current.id !== item.id); feedback.value = "Saved search deleted. It will no longer send updates." } catch { error.value = "Could not delete this search." } finally { actingId.value = null } }
const beginEdit = (item: SavedSearchIntent) => { editingId.value = item.id; editingQuery.value = item.query }
const saveEdit = async (item: SavedSearchIntent) => { if (!editingQuery.value.trim()) return; actingId.value = item.id; try { const updated = await userShellApi.updateSavedSearchIntent(item.id, {query: editingQuery.value.trim(), entityFamily: item.entityFamily, paused: item.paused, notifyEnabled: item.notifyEnabled, expiresAt: item.expiresAt}); items.value = items.value.map(current => current.id === updated.id ? updated : current); editingId.value = null; feedback.value = "Saved intent updated." } catch { error.value = "Could not edit this search." } finally { actingId.value = null } }
onMounted(() => void load())
</script>

<template><section class="saved-searches" data-mental-model="need-save-pause-resume"><header><p class="eyebrow">Search</p><h1>Saved searches</h1><p>Saved searches remember a need you want to revisit. Pause stops future updates; deleting removes it completely.</p></header><CollectionToolbar title="Saved needs" :count="items.length" :busy="loading" /><AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error" :message="error" tone="error" retry @retry="load" /><AppStatus v-if="loading" message="Loading saved searches." busy /><AppStatus v-else-if="!items.length" message="No saved searches yet. Save a search when you want to return to that need later." /><div v-else class="list"><SurfaceRow v-for="item in items" :key="item.id" :row="{id: String(item.id), title: item.query, description: item.entityFamily ? `Looking in ${item.entityFamily}` : 'Looking across the workspace', badge: item.paused ? 'Paused' : 'Watching for updates'}"><template #actions><AppButton type="button" tone="secondary" @click="beginEdit(item)">Edit search</AppButton><AppButton type="button" tone="secondary" :loading="actingId === item.id" @click="toggle(item)">{{ item.paused ? "Resume updates" : "Pause updates" }}</AppButton><AppButton type="button" tone="danger" :loading="actingId === item.id" @click="remove(item)">Delete search</AppButton></template></SurfaceRow></div><form v-if="editingId !== null" class="saved-searches__edit" @submit.prevent="saveEdit(items.find(item => item.id === editingId)!)"><input v-model="editingQuery" aria-label="Edit saved search" maxlength="240"><AppButton type="submit" tone="primary" :loading="actingId === editingId">Save changes</AppButton><AppButton type="button" tone="quiet" @click="editingId = null">Cancel</AppButton></form></section></template>

<style scoped>.saved-searches{display:grid;gap:var(--space-3);max-width:none}.eyebrow{margin:0 0 var(--space-1);color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}h1{margin:0;color:var(--text);font-size:var(--text-size-page-title);letter-spacing:var(--tracking-tight)}.saved-searches header p:last-child{color:var(--text-muted)}.list{overflow:hidden;border:1px solid var(--border-subtle);border-radius:var(--radius-surface);background:var(--surface-base)}.list :deep(.surface-row:last-child){border-bottom:0}.saved-searches__danger{color:var(--danger)}</style>
