<script setup lang="ts">
import {computed, onMounted, ref, watch} from "vue"
import type {ThingBorrowRequestResponseDTO, ThingListingRequestDTO, ThingListingResponseDTO} from "../../../contracts/index.ts"
import {userShellApi} from "../api/userShellApi.ts"
import {useRoute} from "vue-router"
import AppDialog from "../components/AppDialog.vue"
import AppStatus from "../components/AppStatus.vue"
import AppCard from "../components/AppCard.vue"
import {confirmAction} from "../composables/useActionDialog.ts"
import ObjectPreviewPanel from "../components/ObjectPreviewPanel.vue"
import {invokeObjectAction} from "../composables/useObjectActions.ts"
import {useSurfaceViewState} from "../composables/useSurfaceViewState.ts"
import {currentUser} from "../../identity/auth.ts"

const route = useRoute()
const mine = ref(route.path.endsWith("/mine"))
const listings = ref<ThingListingResponseDTO[]>([])
const ownerRequests = ref<ThingBorrowRequestResponseDTO[]>([])
const borrowerRequests = ref<ThingBorrowRequestResponseDTO[]>([])
const form = ref<ThingListingRequestDTO | null>(null)
const editingId = ref<number | null>(null)
const borrowId = ref<number | null>(null)
const borrowMessage = ref("")
const isLoading = ref(true)
const isSaving = ref(false)
const error = ref("")
const feedback = ref("")
const title = computed(() => mine.value ? "My things" : "Things to borrow")
const {state: viewState} = useSurfaceViewState("things-discovery", computed(() => currentUser.value?.id), computed(() => route.fullPath))
const previewListing = computed(() => listings.value.find(listing => listing.id === viewState.value.previewId) ?? null)
const previewSummary = ref("")
const openPreview = async (listingId: number) => { viewState.value.selectedId = listingId; viewState.value.previewId = listingId; try { previewSummary.value = (await userShellApi.getThingPreview(listingId)).summary || "No description yet." } catch { previewSummary.value = "This thing is no longer available." } }
const load = async () => { isLoading.value = true; error.value = ""; try { listings.value = (mine.value ? await userShellApi.getMyThingListings() : await userShellApi.getThingListings()).items; if (mine.value) ownerRequests.value = await userShellApi.getThingOwnerBorrowRequests(); else borrowerRequests.value = await userShellApi.getMyThingBorrowRequests() } catch { error.value = "Could not load things." } finally { isLoading.value = false } }
const create = async () => { if (!form.value) return; isSaving.value = true; error.value = ""; try { await userShellApi.createThingListing(form.value); form.value = null; feedback.value = "Thing listed."; await load() } catch { error.value = "Could not create this listing." } finally { isSaving.value = false } }
const requestBorrow = async () => { if (!borrowId.value) return; isSaving.value = true; error.value = ""; try { await userShellApi.requestThingBorrow(borrowId.value, borrowMessage.value); borrowId.value = null; borrowMessage.value = ""; feedback.value = "Borrow request sent."; await load() } catch { error.value = "Could not request this thing." } finally { isSaving.value = false } }
const cancelBorrow = async (requestId: number) => { if (!await confirmAction("Cancel this borrow request?", "Cancel borrow request")) return; isSaving.value = true; error.value = ""; try { await userShellApi.cancelThingBorrow(requestId); feedback.value = "Borrow request cancelled."; await load() } catch { error.value = "Could not cancel this request." } finally { isSaving.value = false } }
const decideBorrow = async (requestId: number, approve: boolean) => { isSaving.value = true; error.value = ""; try { await userShellApi.decideThingBorrow(requestId, approve); feedback.value = approve ? "Borrow request approved." : "Borrow request declined."; await load() } catch { error.value = "Could not update this request." } finally { isSaving.value = false } }
const returnBorrow = async (requestId: number) => { isSaving.value = true; error.value = ""; try { await userShellApi.returnThingBorrow(requestId); feedback.value = "Thing marked as returned."; await load() } catch { error.value = "Could not mark this thing as returned." } finally { isSaving.value = false } }
const editListing = (listing: ThingListingResponseDTO) => { form.value = {title: listing.title, description: listing.description || "", conditionNote: listing.conditionNote || "", available: listing.available}; editingId.value = listing.id }
const saveListing = async () => { if (!form.value || editingId.value === null) return; isSaving.value = true; error.value = ""; try { await userShellApi.updateThingListing(editingId.value, form.value); form.value = null; editingId.value = null; feedback.value = "Thing listing updated."; await load() } catch { error.value = "Could not update this listing." } finally { isSaving.value = false } }
const archiveListing = async (listing: ThingListingResponseDTO) => { await invokeObjectAction({id: `archive-${listing.id}`, label: "Archive", tone: "danger", confirmation: {title: "Archive listing", message: `Archive “${listing.title}”?`}, run: async () => { isSaving.value = true; error.value = ""; try { await userShellApi.archiveThingListing(listing.id); feedback.value = "Thing listing archived."; await load() } catch { error.value = "Could not archive this listing." } finally { isSaving.value = false } }}) }
watch(() => route.path, (path) => { mine.value = path.endsWith("/mine"); void load() })
watch(() => route.query.create, (value) => { if (value === "1" && !form.value) form.value = {title: "", description: "", conditionNote: "", available: true} }, {immediate: true})
onMounted(() => void load())
</script>

<template>
  <section class="things-surface">
    <header><div><p class="eyebrow">Things</p><h1>{{ title }}</h1></div><div class="actions"><button type="button" :class="{active: !mine}" @click="mine = false; void load()">Discover</button><button type="button" :class="{active: mine}" @click="mine = true; void load()">My things</button><button type="button" class="primary" @click="form = {title: '', description: '', conditionNote: '', available: true}">List a thing</button></div></header>
    <AppStatus v-if="feedback" :message="feedback" tone="success" /><AppStatus v-if="error" :message="error" tone="error" retry @retry="load" />
    <AppStatus v-if="isLoading" message="Loading." /><AppStatus v-else-if="listings.length === 0" message="No things are available yet." />
    <div v-else class="things-workspace"><div class="listing-grid"><AppCard v-for="listing in listings" :key="listing.id" :to="`/things/${listing.id}`" :label="listing.title" :previewed="previewListing?.id === listing.id" class="listing" @preview="openPreview(listing.id)"><router-link :to="`/things/${listing.id}`" class="listing__link"><div><p class="listing__owner">{{ listing.ownerUsername }}</p><h2>{{ listing.title }}</h2><p>{{ listing.description || "No description yet." }}</p><small>{{ listing.conditionNote || "Condition not specified" }}</small></div></router-link><div v-if="mine" class="listing__owner-actions"><button type="button" @click="editListing(listing)">Edit</button><button type="button" @click="archiveListing(listing)">Archive</button></div><button v-else-if="!listing.myPendingRequestId" type="button" @click="borrowId = listing.id">Request to borrow</button><div v-else class="pending"><span>Request pending</span><button type="button" @click="cancelBorrow(listing.myPendingRequestId!)">Cancel request</button></div><template #actions><button type="button" @click="openPreview(listing.id)">Preview</button></template></AppCard></div><ObjectPreviewPanel :title="previewListing?.title ?? 'Thing'" subtitle="Thing preview" :open="previewListing !== null" @close="viewState.previewId = null" @open-detail="previewListing && $router.push(`/things/${previewListing.id}`)"><p v-if="previewListing">{{ previewSummary || previewListing.description || 'No description yet.' }}</p><p v-if="previewListing">{{ previewListing.conditionNote || 'Condition not specified' }}</p></ObjectPreviewPanel></div>
    <section v-if="!mine && borrowerRequests.length" class="requests"><h2>My borrow requests</h2><article v-for="request in borrowerRequests" :key="request.id" class="request"><div><strong>{{ request.borrowerUsername }} · {{ request.status }}</strong><small>Listing #{{ request.listingId }}</small></div><button v-if="request.status === 'APPROVED'" type="button" @click="returnBorrow(request.id)">Mark returned</button><button v-else-if="request.status === 'PENDING'" type="button" @click="cancelBorrow(request.id)">Cancel</button></article></section>
    <section v-if="mine && ownerRequests.length" class="requests"><h2>Borrow requests for my things</h2><article v-for="request in ownerRequests" :key="request.id" class="request"><div><strong>{{ request.borrowerUsername }} · {{ request.status }}</strong><small>Listing #{{ request.listingId }}<template v-if="request.message"> · {{ request.message }}</template></small></div><div v-if="request.status === 'PENDING'" class="request__actions"><button type="button" :disabled="isSaving" @click="decideBorrow(request.id, true)">Approve</button><button type="button" :disabled="isSaving" @click="decideBorrow(request.id, false)">Decline</button></div></article></section>
    <AppDialog :open="form !== null" :title="editingId === null ? 'List a thing' : 'Edit listing'" @close="form = null; editingId = null"><form class="form" @submit.prevent="editingId === null ? create() : saveListing()"><label>Title<input v-model="form!.title" required maxlength="140"></label><label>Description<textarea v-model="form!.description" maxlength="2000"></textarea></label><label>Condition note<input v-model="form!.conditionNote" maxlength="180"></label><label class="availability"><input v-model="form!.available" type="checkbox"> Available to borrow</label><div><button class="primary" type="submit" :disabled="isSaving">{{ isSaving ? "Saving" : editingId === null ? "Save listing" : "Update listing" }}</button><button type="button" @click="form = null; editingId = null">Cancel</button></div></form></AppDialog>
    <AppDialog :open="borrowId !== null" title="Request to borrow" @close="borrowId = null"><form class="form" @submit.prevent="requestBorrow"><label>Message<textarea v-model="borrowMessage" maxlength="1000" placeholder="Add a note for the owner."></textarea></label><div><button class="primary" type="submit" :disabled="isSaving">{{ isSaving ? "Sending" : "Send request" }}</button><button type="button" @click="borrowId = null">Cancel</button></div></form></AppDialog>
  </section>
</template>

<style scoped>
.things-surface{display:grid;gap:1rem;max-width:72rem}.things-surface header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.eyebrow,.listing__owner{margin:0 0 .3rem;color:var(--text-soft);font-size:.76rem;font-weight:650;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.55rem,2.5vw,2.3rem);letter-spacing:-.075em}h2{margin:.2rem 0;font-size:1.1rem}.actions{display:flex;gap:.35rem;flex-wrap:wrap}.things-surface button{border:1px solid var(--border-subtle);border-radius:999px;padding:.5rem .75rem;background:transparent;color:var(--text);font:inherit;cursor:pointer}.things-surface button.active,.things-surface button.primary{background:var(--accent);color:#121217}.things-workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(18rem,24rem);border:1px solid var(--border-subtle);border-radius:var(--radius-card);overflow:hidden}.listing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;padding:.75rem}.listing{display:grid;gap:.7rem;padding:1rem}.listing__link{display:block}.listing p{color:var(--text-muted)}.listing small,.pending,.request small{color:var(--text-soft)}.status{padding:.7rem 0;color:var(--text-muted)}.status--error{color:var(--danger)}.status--success{color:var(--success)}.status button{border:0;text-decoration:underline;padding:0}.form{display:grid;gap:.75rem;padding:1rem;border-top:1px solid var(--border-subtle)}.form label{display:grid;gap:.35rem;font-weight:650}.form input,.form textarea{border:1px solid var(--border-subtle);border-radius:.65rem;padding:.65rem;background:var(--bg-raised);color:var(--text);font:inherit}.form textarea{min-height:5rem}.requests{display:grid;gap:.5rem;border-top:1px solid var(--border-subtle);padding-top:1rem}.request{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:.75rem 0;border-bottom:1px solid var(--border-subtle)}.request>div:first-child{display:grid;gap:.25rem}.request__actions{display:flex;gap:.35rem}@media(max-width:860px){.things-workspace{grid-template-columns:1fr}.things-workspace :deep(.object-preview){border-left:0;border-top:1px solid var(--border-subtle)}}@media(max-width:650px){.things-surface header{align-items:start;flex-direction:column}.listing-grid{grid-template-columns:1fr}.request{align-items:start;flex-direction:column}}
</style>
