create table chat_conversation (
    id bigint generated by default as identity primary key,
    left_participant_id bigint not null,
    right_participant_id bigint not null,
    created_at timestamp with time zone not null default current_timestamp,
    last_message_at timestamp with time zone,
    last_message_preview varchar(240),
    last_message_sender_id bigint,
    last_message_has_image boolean not null default false,
    constraint fk_chat_conversation_left_participant
        foreign key (left_participant_id) references app_user(id),
    constraint fk_chat_conversation_right_participant
        foreign key (right_participant_id) references app_user(id),
    constraint fk_chat_conversation_last_message_sender
        foreign key (last_message_sender_id) references app_user(id),
    constraint uk_chat_conversation_pair
        unique (left_participant_id, right_participant_id)
);

create index idx_chat_conversation_left_participant
    on chat_conversation(left_participant_id);

create index idx_chat_conversation_right_participant
    on chat_conversation(right_participant_id);

create index idx_chat_conversation_last_message_at
    on chat_conversation(last_message_at desc);

create table chat_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    sender_user_id bigint not null,
    message_body varchar(2000),
    image_data_url text,
    created_at timestamp with time zone not null default current_timestamp,
    read_at timestamp with time zone,
    constraint fk_chat_message_conversation
        foreign key (conversation_id) references chat_conversation(id) on delete cascade,
    constraint fk_chat_message_sender
        foreign key (sender_user_id) references app_user(id)
);

create index idx_chat_message_conversation_created_at
    on chat_message(conversation_id, created_at);

create index idx_chat_message_conversation_read_at
    on chat_message(conversation_id, read_at);

create table chat_presence (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    last_active_at timestamp with time zone not null,
    constraint fk_chat_presence_user
        foreign key (user_id) references app_user(id) on delete cascade,
    constraint uk_chat_presence_user
        unique (user_id)
);

create index idx_chat_presence_last_active_at
    on chat_presence(last_active_at desc);
