create table chat_conversation_member_state (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    user_id bigint not null,
    muted_until timestamp with time zone,
    archived_at timestamp with time zone,
    last_opened_at timestamp with time zone,
    last_delivered_message_id bigint,
    last_delivered_at timestamp with time zone,
    last_seen_message_id bigint,
    last_seen_at timestamp with time zone,
    constraint fk_chat_conversation_member_state_conversation
        foreign key (conversation_id) references chat_conversation(id) on delete cascade,
    constraint fk_chat_conversation_member_state_user
        foreign key (user_id) references app_user(id) on delete cascade,
    constraint uk_chat_conversation_member_state
        unique (conversation_id, user_id)
);

create index idx_chat_conversation_member_state_user
    on chat_conversation_member_state(user_id, archived_at);

alter table chat_message
    add column delivered_at timestamp with time zone,
    add column seen_at timestamp with time zone;

update chat_message
set delivered_at = coalesce(read_at, created_at),
    seen_at = read_at
where read_at is not null;

create index idx_chat_message_conversation_seen_at
    on chat_message(conversation_id, seen_at);

create index idx_chat_message_conversation_delivered_at
    on chat_message(conversation_id, delivered_at);

create table chat_audit_event (
    id bigint generated by default as identity primary key,
    event_type varchar(48) not null,
    user_id bigint,
    conversation_id bigint,
    session_id varchar(80),
    remote_address varchar(120),
    user_agent varchar(255),
    details_json text,
    created_at timestamp with time zone not null default current_timestamp,
    constraint fk_chat_audit_event_user
        foreign key (user_id) references app_user(id) on delete set null,
    constraint fk_chat_audit_event_conversation
        foreign key (conversation_id) references chat_conversation(id) on delete set null
);

create index idx_chat_audit_event_created_at
    on chat_audit_event(created_at desc);

create index idx_chat_audit_event_user_created_at
    on chat_audit_event(user_id, created_at desc);
