alter table chat_conversation
    alter column left_participant_id drop not null;

alter table chat_conversation
    alter column right_participant_id drop not null;

alter table chat_conversation
    add column conversation_type varchar(48) not null default 'DIRECT',
    add column context_type varchar(48),
    add column context_id bigint,
    add column title varchar(160),
    add column owner_user_id bigint,
    add column created_by_user_id bigint;

alter table chat_conversation
    add constraint fk_chat_conversation_owner_user
        foreign key (owner_user_id) references app_user(id) on delete set null;

alter table chat_conversation
    add constraint fk_chat_conversation_created_by_user
        foreign key (created_by_user_id) references app_user(id) on delete set null;

update chat_conversation
set owner_user_id = left_participant_id,
    created_by_user_id = left_participant_id
where conversation_type = 'DIRECT';

create table chat_conversation_participant (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    user_id bigint not null,
    role varchar(32) not null,
    added_by_user_id bigint,
    joined_at timestamp with time zone not null default current_timestamp,
    constraint fk_chat_conversation_participant_conversation
        foreign key (conversation_id) references chat_conversation(id) on delete cascade,
    constraint fk_chat_conversation_participant_user
        foreign key (user_id) references app_user(id) on delete cascade,
    constraint fk_chat_conversation_participant_added_by_user
        foreign key (added_by_user_id) references app_user(id) on delete set null,
    constraint uk_chat_conversation_participant
        unique (conversation_id, user_id)
);

insert into chat_conversation_participant (conversation_id, user_id, role, added_by_user_id, joined_at)
select id, left_participant_id, 'OWNER', left_participant_id, created_at
from chat_conversation
where left_participant_id is not null;

insert into chat_conversation_participant (conversation_id, user_id, role, added_by_user_id, joined_at)
select id, right_participant_id, 'MEMBER', left_participant_id, created_at
from chat_conversation
where right_participant_id is not null;

create index idx_chat_conversation_context
    on chat_conversation(context_type, context_id);

create unique index uk_chat_conversation_context
    on chat_conversation(context_type, context_id)
    where context_type is not null
      and context_id is not null;

create index idx_chat_conversation_type
    on chat_conversation(conversation_type, coalesce(last_message_at, created_at) desc);

create index idx_chat_conversation_participant_user
    on chat_conversation_participant(user_id, conversation_id);
