DROP TABLE IF EXISTS public.quest_application CASCADE;
DROP TABLE IF EXISTS public.quest CASCADE;
DROP TABLE IF EXISTS public.app_user CASCADE;

CREATE TABLE public.app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE public.quest
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id   BIGINT       NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),
    award_amount NUMERIC(10, 2),
    status       VARCHAR(255) NOT NULL,

    CONSTRAINT fk_quest_creator
        FOREIGN KEY (creator_id)
            REFERENCES public.app_user (id)
);

CREATE TABLE public.quest_application
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id       BIGINT       NOT NULL,
    applicant_id   BIGINT       NOT NULL,
    message        VARCHAR(2000),
    proposed_price NUMERIC(10, 2),
    status         VARCHAR(255) NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_quest_application_quest
        FOREIGN KEY (quest_id)
            REFERENCES public.quest (id),

    CONSTRAINT fk_quest_application_applicant
        FOREIGN KEY (applicant_id)
            REFERENCES public.app_user (id),

    CONSTRAINT uk_quest_application_quest_applicant
        UNIQUE (quest_id, applicant_id)
);