create table commute_preference (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    enabled boolean not null default false,
    consent_granted boolean not null default false,
    home_area varchar(160),
    work_area varchar(160),
    weekdays varchar(32),
    departure_time time,
    return_time time,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_commute_preference_user foreign key (user_id) references app_user(id)
);
