create table saved_search_intent (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    query_text varchar(240) not null,
    entity_family varchar(40),
    paused boolean not null default false,
    notify_enabled boolean not null default true,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_saved_search_owner foreign key (owner_id) references app_user(id)
);
create index idx_saved_search_owner on saved_search_intent(owner_id, paused, expires_at);
