create table safety_report (
    id bigint generated by default as identity primary key,
    reporter_id bigint not null,
    target_user_id bigint,
    target_family varchar(40) not null,
    target_id bigint,
    reason varchar(1000) not null,
    status varchar(24) not null default 'OPEN',
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_safety_report_reporter foreign key (reporter_id) references app_user(id),
    constraint fk_safety_report_target_user foreign key (target_user_id) references app_user(id)
);
create index idx_safety_report_reporter on safety_report(reporter_id, created_at);
