create table onboarding_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    current_step varchar(48) not null,
    skipped boolean not null default false,
    completed boolean not null default false,
    updated_at timestamp with time zone not null,
    constraint fk_onboarding_user foreign key (user_id) references app_user(id)
);
