create table activity_resume_dismissal (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    resume_key varchar(160) not null,
    created_at timestamp with time zone not null,
    constraint uq_activity_resume_dismissal unique(user_id, resume_key),
    constraint fk_activity_resume_user foreign key (user_id) references app_user(id)
);
