CREATE TABLE workspace_rail_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL UNIQUE,
    rail_width_px INTEGER NOT NULL,
    CONSTRAINT fk_workspace_rail_preference_owner FOREIGN KEY (owner_id) REFERENCES app_user(id),
    CONSTRAINT chk_workspace_rail_preference_width CHECK (rail_width_px BETWEEN 216 AND 280)
);
