CREATE TABLE password_recovery_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_password_recovery_token_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_password_recovery_token_user ON password_recovery_token(user_id);
CREATE INDEX idx_password_recovery_token_expiry ON password_recovery_token(expires_at);
