CREATE TABLE appearance_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL UNIQUE,
    theme VARCHAR(16) NOT NULL,
    CONSTRAINT fk_appearance_preference_owner FOREIGN KEY (owner_id) REFERENCES app_user(id),
    CONSTRAINT chk_appearance_preference_theme CHECK (theme IN ('SYSTEM', 'DARK', 'LIGHT'))
);
