package com.themuffinman.app.vision.model;

public enum QuestNewsType {
    CIRCLE_REQUEST_RECEIVED,
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_WITHDRAWN,
    APPLICATION_APPROVED,
    APPLICATION_DECLINED,
    QUEST_TERM_CONFIRMATION_REQUESTED,
    QUEST_TERM_CONFIRMED,
    QUEST_TERM_REJECTED,
    QUEST_STARTED,
    QUEST_COMPLETED,
    QUEST_REOPENED,
    QUEST_DELETED,
    CIRCLE_REQUEST_ACCEPTED
}
