package com.themuffinman.app.vision.model;

public enum VisionIntent {
    CREATE_QUEST,
    CREATE_CIRCLE,
    CREATE_CIRCLE_REQUEST,
    ACCEPT_CIRCLE_REQUEST,
    DELETE_CIRCLE_REQUEST,
    CREATE_APPLICATION,
    UPDATE_APPLICATION,
    WITHDRAW_APPLICATION,
    APPROVE_APPLICATION,
    DECLINE_APPLICATION,
    UPDATE_CIRCLE,
    DELETE_CIRCLE,
    UPDATE_PROFILE,
    UPDATE_PROFILE_LOCATION,
    DISCOVER_QUESTS,
    OPEN_CHAT,
    VIEW_PROFILE,
    VIEW_CIRCLES,
    VIEW_APPLICATIONS,
    UNSUPPORTED
}
