import {computed} from "vue"
import {useRoute, useRouter} from "vue-router"
import {currentUser, isAdmin} from "../../../auth.ts"
import {
  parseInstantFromInput
} from "../../../shared/questSchedule.ts"
import {
  dashboardTabs
} from "../domain/workmarketDomain.ts"
import {createDashboardDataState} from "./dashboard/createDashboardDataState.ts"
import {createDashboardErrorState} from "./dashboard/createDashboardErrorState.ts"
import {createDashboardInteractions} from "./dashboard/createDashboardInteractions.ts"
import {createDashboardOptionState} from "./dashboard/createDashboardOptionState.ts"
import {createDashboardProfileState} from "./dashboard/createDashboardProfileState.ts"
import {createDashboardQuestState} from "./dashboard/createDashboardQuestState.ts"
import {createDashboardSelectors} from "./dashboard/createDashboardSelectors.ts"
import {createDashboardTabState} from "./dashboard/createDashboardTabState.ts"

export const useQuestDashboardState = () => {
  const route = useRoute()
  const router = useRouter()

  const {activeTab} = createDashboardTabState(route)
  const {
    quests,
    dashboardMyQuests,
    dashboardAvailableQuests,
    myApplications,
    newsItems,
    unreadNewsCount,
    dashboardOptions,
    dashboardSummary,
    dashboardSections,
    incomingCircleRequests,
    circles,
    appUsers,
    applicationsByQuestId,
    isLoadingQuests,
    isLoadingApplications,
    isLoadingNews,
    isLoadingUsers,
    questsError,
    questsErrorDetails,
    applicationsError,
    applicationsErrorDetails,
    newsError,
    newsErrorDetails,
    usersError,
    usersErrorDetails
  } = createDashboardDataState()
  const {
    questStatusFilterOptions,
    questApplicationStatusFilterOptions,
    questStatusOptions,
    questAudienceOptions,
    questAudienceFilterOptions,
    questSortOptions
  } = createDashboardOptionState(dashboardOptions)
  const {
    copiedDebugBanner,
    copiedDebug,
    feedback,
    feedbackType,
    showFeedback: showProfileFeedback,
    isProfileEditDialogOpen,
    isNotificationsDialogOpen,
    successPulseTarget,
    profileUsername,
    profileDescription,
    profileAvatarDataUrl,
    accountCreatedAt
  } = createDashboardProfileState()
  const {
    questTitle,
    questDescription,
    questAwardAmount,
    questScheduledAt,
    questEndsAt,
    questTermMode,
    questTermFixed,
    questAudience,
    questSelectedCircleIds,
    questCreatorId,
    questImages,
    adminQuestStatusFilter,
    applicationMessages,
    proposedPrices,
    openApplicationsQuestIds,
    showAllApplicationsQuestIds,
    questDisclosureRefs,
    editingQuestId,
    editQuestTitle,
    editQuestDescription,
    editQuestAwardAmount,
    editQuestScheduledAt,
    editQuestEndsAt,
    editQuestTermMode,
    editQuestTermFixed,
    editQuestAudience,
    editQuestSelectedCircleIds,
    editQuestCreatorId,
    editQuestStatus,
    editingApplicationId,
    editApplicationMessage,
    editApplicationPrice,
    overviewFocus,
    questDialogId,
    applicationDialogId,
    userProfileDialogId,
    isCreateJobDialogOpen,
    isFindWorkDialogOpen,
    isOpenWorkDialogOpen,
    isApplicationsDialogOpen
  } = createDashboardQuestState()
  const selectors = createDashboardSelectors({
    activeTab,
    quests,
    dashboardMyQuests,
    dashboardAvailableQuests,
    myApplications,
    newsItems,
    dashboardSummary,
    dashboardSections,
    incomingCircleRequests,
    adminQuestStatusFilter,
    applicationsByQuestId,
    questDialogId,
    applicationDialogId,
    dashboardTabs
  })
  const {
    sectionTitle,
    sectionSubtitle,
    recentMyQuests,
    recentMyApplications,
    activeWorkApplications,
    pendingWorkApplications,
    visibleMyQuestsCount,
    pendingWorkApplicationsCount,
    activeWorkApplicationsCount,
    activeMyQuestsCount,
    activeWorkCount,
    incomingWorkQuests,
    outgoingWorkApplications,
    visibleMyQuests,
    visibleMyApplications,
    recentNewsItems,
    unreadNewsItems,
    recentIncomingCircleRequests,
    applicationsViewForQuest,
    applicationsForQuest,
    questForId,
    selectedQuestDialog,
    selectedApplicationDialog,
    questCreatorUsernameForQuest,
    featuredApplicationForQuest,
    hiddenApplicationsCountForQuest,
    canRevealHiddenApplicationsForQuest,
    showAllApplicationsForQuest,
    applicationRevealLabel
  } = selectors
  const adminModeEnabled = computed(() => dashboardSummary.value?.adminModeEnabled ?? false)

  const interactions = createDashboardInteractions({
    route,
    router,
    adminModeEnabled,
    activeTab,
    overviewFocus,
    profileUsername,
    profileDescription,
    profileAvatarDataUrl,
    isProfileEditDialogOpen,
    isNotificationsDialogOpen,
    questDialogId,
    applicationDialogId,
    userProfileDialogId,
    isCreateJobDialogOpen,
    isFindWorkDialogOpen,
    isOpenWorkDialogOpen,
    isApplicationsDialogOpen,
    applicationMessages,
    proposedPrices,
    questDisclosureRefs,
    editingQuestId,
    openApplicationsQuestIds,
    showAllApplicationsQuestIds,
    editingApplicationId,
    editApplicationMessage,
    editApplicationPrice,
    editQuestTitle,
    editQuestDescription,
    editQuestAwardAmount,
    editQuestScheduledAt,
    editQuestEndsAt,
    editQuestTermMode,
    editQuestTermFixed,
    editQuestAudience,
    editQuestSelectedCircleIds,
    editQuestCreatorId,
    editQuestStatus,
    questTitle,
    questDescription,
    questAwardAmount,
    questScheduledAt,
    questEndsAt,
    questTermMode,
    questTermFixed,
    questAudience,
    questSelectedCircleIds,
    questCreatorId,
    showFeedback: showProfileFeedback,
    successPulseTarget,
    copiedDebugBanner,
    questForId,
    myApplications
  })
  const {
    setQuestTermMode,
    setEditQuestTermMode,
    showFeedback: showDashboardFeedback,
    triggerSuccessPulse,
    setActiveTab,
    goToTab,
    toggleOverviewFocus,
    clearOverviewFocus,
    openProfileEditDialog,
    closeProfileEditDialog,
    openNotificationsDialog,
    closeNotificationsDialog,
    closeQuestDialog,
    closeApplicationDialog,
    openUserProfileDialog,
    closeUserProfileDialog,
    openCreateJobDialog,
    closeCreateJobDialog,
    openFindWorkDialog,
    closeFindWorkDialog,
    openOpenWorkDialog,
    closeOpenWorkDialog,
    openApplicationsDialog,
    closeApplicationsDialog,
    registerQuestDisclosure,
    closeQuestDisclosure,
    openQuestDisclosure,
    toggleApplicationsForQuest,
    toggleQuestDisclosure,
    handleDocumentClick,
    startEditingApplication,
    handleApplicationDisclosureToggle,
    cancelEditingApplication,
    startEditingQuest,
    reopenQuest,
    cancelEditingQuest,
    copyDebugInfo
  } = interactions

  const {resetErrorState} = createDashboardErrorState({
    questsError,
    questsErrorDetails,
    applicationsError,
    applicationsErrorDetails,
    newsError,
    newsErrorDetails,
    usersError,
    usersErrorDetails
  })

  const init = () => undefined

  return {
    activeTab,
    sectionTitle,
    sectionSubtitle,
    quests,
    dashboardMyQuests,
    dashboardAvailableQuests,
    myApplications,
    newsItems,
    unreadNewsCount,
    dashboardOptions,
    dashboardSummary,
    dashboardSections,
    incomingCircleRequests,
    circles,
    appUsers,
    isLoadingQuests,
    isLoadingApplications,
    isLoadingNews,
    isLoadingUsers,
    questsError,
    questsErrorDetails,
    applicationsError,
    applicationsErrorDetails,
    newsError,
    newsErrorDetails,
    usersError,
    usersErrorDetails,
    feedback,
    feedbackType,
    copiedDebug,
    isProfileEditDialogOpen,
    isNotificationsDialogOpen,
    successPulseTarget,
    currentUser,
    adminModeEnabled,
    isAdmin,
    questTitle,
    questDescription,
    questAwardAmount,
    questScheduledAt,
    questEndsAt,
    questTermFixed,
    questTermMode,
    questAudience,
    questSelectedCircleIds,
    questCreatorId,
    questImages,
    profileUsername,
    profileDescription,
    profileAvatarDataUrl,
    accountCreatedAt,
    adminQuestStatusFilter,
    applicationMessages,
    proposedPrices,
    applicationsByQuestId,
    openApplicationsQuestIds,
    showAllApplicationsQuestIds,
    questDisclosureRefs,
    editingQuestId,
    editQuestTitle,
    editQuestDescription,
    editQuestAwardAmount,
    editQuestScheduledAt,
    editQuestEndsAt,
    editQuestTermFixed,
    editQuestTermMode,
    editQuestAudience,
    editQuestSelectedCircleIds,
    editQuestCreatorId,
    editQuestStatus,
    editingApplicationId,
    editApplicationMessage,
    editApplicationPrice,
    overviewFocus,
    questDialogId,
    applicationDialogId,
    userProfileDialogId,
    isCreateJobDialogOpen,
    isFindWorkDialogOpen,
    isOpenWorkDialogOpen,
    isApplicationsDialogOpen,
    questStatusOptions,
    questStatusFilterOptions,
    questApplicationStatusFilterOptions,
    questAudienceOptions,
    questAudienceFilterOptions,
    questSortOptions,
    dashboardTabs,
    recentMyQuests,
    recentMyApplications,
    activeWorkApplications,
    pendingWorkApplications,
    visibleMyQuestsCount,
    pendingWorkApplicationsCount,
    activeWorkApplicationsCount,
    activeMyQuestsCount,
    activeWorkCount,
    incomingWorkQuests,
    outgoingWorkApplications,
    visibleMyQuests,
    visibleMyApplications,
    recentNewsItems,
    unreadNewsItems,
    recentIncomingCircleRequests,
    applicationsForQuest,
    questForId,
    selectedQuestDialog,
    selectedApplicationDialog,
    questCreatorUsernameForQuest,
    showAllApplicationsForQuest,
    applicationsViewForQuest,
    featuredApplicationForQuest,
    hiddenApplicationsCountForQuest,
    canRevealHiddenApplicationsForQuest,
    applicationRevealLabel,
    parseInstantFromInput,
    setQuestTermMode,
    setEditQuestTermMode,
    showFeedback: showDashboardFeedback,
    triggerSuccessPulse,
    setActiveTab,
    goToTab,
    toggleOverviewFocus,
    clearOverviewFocus,
    openProfileEditDialog,
    closeProfileEditDialog,
    openNotificationsDialog,
    closeNotificationsDialog,
    closeQuestDialog,
    closeApplicationDialog,
    openUserProfileDialog,
    closeUserProfileDialog,
    openCreateJobDialog,
    closeCreateJobDialog,
    openFindWorkDialog,
    closeFindWorkDialog,
    openOpenWorkDialog,
    closeOpenWorkDialog,
    openApplicationsDialog,
    closeApplicationsDialog,
    registerQuestDisclosure,
    closeQuestDisclosure,
    openQuestDisclosure,
    toggleApplicationsForQuest,
    toggleQuestDisclosure,
    handleDocumentClick,
    startEditingApplication,
    handleApplicationDisclosureToggle,
    cancelEditingApplication,
    startEditingQuest,
    reopenQuest,
    cancelEditingQuest,
    resetErrorState,
    copyDebugInfo,
    init
  }
}

export type QuestDashboardState = ReturnType<typeof useQuestDashboardState>
