<script setup lang="ts">
import type {BusinessPublicAvailabilityCalendarDTO} from "../../../contracts/index.ts"
// Calendar communicates availability in text as well as visually.
type CalendarView = "MONTH" | "WEEK" | "DAY"
defineProps<{calendar: BusinessPublicAvailabilityCalendarDTO | null; selectedDate: string; view: CalendarView}>()
const emit = defineEmits<{select: [date: string]; previous: []; next: []; changeView: [view: CalendarView]}>()
</script>
<template><section v-if="calendar" class="calendar" aria-label="Service availability calendar"><header><div><h3>{{ view[0] + view.slice(1).toLowerCase() }} availability</h3><p>Choose an available day. Times are shown in {{ calendar.timezone }}.</p></div><div class="calendar__views" role="group" aria-label="Calendar view"><button v-for="item in ['MONTH','WEEK','DAY']" :key="item" type="button" :aria-pressed="view === item" @click="emit('changeView', item as CalendarView)">{{ item[0] + item.slice(1).toLowerCase() }}</button></div></header><div class="calendar__range"><button type="button" aria-label="Previous calendar range" @click="emit('previous')">‹</button><strong>{{ calendar.fromDate }} – {{ calendar.toDate }}</strong><button type="button" aria-label="Next calendar range" @click="emit('next')">›</button></div><div :class="['calendar__days', `calendar__days--${view.toLowerCase()}`]"><button v-for="day in calendar.days" :key="day.date" type="button" :disabled="day.availabilityState === 'UNAVAILABLE'" :aria-pressed="selectedDate === day.date" :aria-label="`${day.date}: ${day.availabilityState === 'UNAVAILABLE' ? 'Unavailable' : `${day.availableSlotCount} available times`}`" @click="emit('select', day.date)"><strong>{{ day.date }}</strong><span>{{ day.availabilityState === 'UNAVAILABLE' ? 'Unavailable' : day.availabilityState === 'LIMITED' ? 'Limited availability' : `${day.availableSlotCount} times available` }}</span></button></div></section></template>
<style scoped>.calendar{display:grid;gap:var(--space-2);min-width:0}.calendar header,.calendar__range,.calendar__views{display:flex;align-items:center;justify-content:space-between;gap:var(--space-2);flex-wrap:wrap}.calendar h3,.calendar p{margin:0}.calendar p{color:var(--text-muted)}.calendar__days{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:var(--space-1)}.calendar__days--week{grid-template-columns:repeat(7,minmax(0,1fr))}.calendar__days--day{grid-template-columns:1fr}button{border:1px solid var(--border-subtle);border-radius:var(--radius-control);background:var(--surface-base);color:var(--text);font:inherit;padding:var(--space-1);cursor:pointer} .calendar__days button{display:grid;gap:var(--space-1);min-height:4.5rem;text-align:left}.calendar__views button[aria-pressed="true"],.calendar__days button[aria-pressed="true"]{outline:2px solid var(--accent)}button:disabled{color:var(--text-muted);cursor:not-allowed}.calendar span{font-size:var(--text-size-meta)}@media(max-width:640px){.calendar__days{grid-template-columns:repeat(3,minmax(0,1fr))}.calendar__days--week,.calendar__days--day{grid-template-columns:1fr}}</style>
