<script setup lang="ts">
import {computed} from "vue"
import type {CalendarEvent} from "../../../contracts/index.ts"
import type {CalendarDay} from "../../../services/calendarTime.ts"
import {useCalendarLayout} from "../composables/useCalendarLayout.ts"

const props = defineProps<{mode: "week" | "month"; days: CalendarDay[]; selectedDay: string; events: CalendarEvent[]; timezone: string; sourceLabel: (source: string) => string}>()
const emit = defineEmits<{"update:selectedDay": [string]; select: [CalendarEvent]}>()
const {eventsForDay} = useCalendarLayout(() => props.timezone)
const selected = computed(() => props.days.find(day => day.key === props.selectedDay) ?? props.days[0])
const selectedEvents = computed(() => selected.value ? eventsForDay(props.events, selected.value).sort((left, right) => new Date(left.startsAt).getTime() - new Date(right.startsAt).getTime()) : [])
const countFor = (day: CalendarDay) => eventsForDay(props.events, day).length
</script>

<template>
  <section class="calendar-mobile-agenda" :class="`calendar-mobile-agenda--${mode}`" :aria-label="`${mode} calendar agenda`"><div v-if="mode === 'week'" class="calendar-mobile-agenda__day-strip" role="tablist" aria-label="Days this week"><button v-for="day in days" :key="day.key" type="button" :class="{active: selected?.key === day.key}" :aria-selected="selected?.key === day.key" @click="emit('update:selectedDay', day.key)"><small>{{ day.weekday }}</small><strong>{{ day.label.split(' ')[0] }}</strong><i v-if="countFor(day)" /></button></div><div v-else class="calendar-mobile-agenda__month-grid" role="grid" aria-label="Days this month"><button v-for="day in days" :key="day.key" type="button" :class="{active: selected?.key === day.key}" :aria-selected="selected?.key === day.key" @click="emit('update:selectedDay', day.key)"><span>{{ day.label.split(' ')[0] }}</span><i v-if="countFor(day)">{{ countFor(day) }}</i></button></div><header><p>{{ mode === 'week' ? 'Selected day' : 'Selected date' }}</p><h2>{{ selected ? `${selected.weekday}, ${selected.label}` : 'Choose a day' }}</h2></header><div class="calendar-mobile-agenda__items"><button v-for="event in selectedEvents" :key="event.eventKey" type="button" @click="emit('select', event)"><time>{{ event.allDay ? 'All day' : new Intl.DateTimeFormat(undefined, {timeZone: timezone, hour: 'numeric', minute: '2-digit'}).format(new Date(event.startsAt)) }}</time><span><strong>{{ event.title }}</strong><small>{{ sourceLabel(event.source) }}</small></span></button><p v-if="!selectedEvents.length">Nothing is scheduled for this day.</p></div></section>
</template>

<style scoped>
.calendar-mobile-agenda{display:none}@media(max-width:700px){.calendar-mobile-agenda{display:grid;gap:var(--space-3)}.calendar-mobile-agenda__day-strip{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:var(--space-1)}.calendar-mobile-agenda__day-strip button,.calendar-mobile-agenda__month-grid button{display:grid;place-items:center;gap:.15rem;min-height:3.4rem;border:1px solid var(--border-subtle);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text);font:inherit;cursor:pointer}.calendar-mobile-agenda__day-strip button.active,.calendar-mobile-agenda__month-grid button.active{border-color:var(--accent);background:var(--accent);color:var(--accent-contrast)}.calendar-mobile-agenda__day-strip small{font-size:var(--text-size-label);color:inherit}.calendar-mobile-agenda__day-strip i{width:.3rem;height:.3rem;border-radius:50%;background:currentColor}.calendar-mobile-agenda__month-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:var(--space-1)}.calendar-mobile-agenda__month-grid button{position:relative;min-height:2.6rem}.calendar-mobile-agenda__month-grid i{position:absolute;right:.2rem;bottom:.15rem;display:grid;place-items:center;min-width:.9rem;height:.9rem;border-radius:50%;background:var(--accent-muted);color:var(--text);font-size:.6rem;font-style:normal}.calendar-mobile-agenda header{display:grid;gap:var(--space-1)}.calendar-mobile-agenda header p{margin:0;color:var(--text-soft);font-size:var(--text-size-label);font-weight:var(--text-weight-semibold);letter-spacing:var(--tracking-label);text-transform:uppercase}.calendar-mobile-agenda h2{margin:0;font-size:var(--text-size-title)}.calendar-mobile-agenda__items{display:grid;gap:var(--space-2)}.calendar-mobile-agenda__items button{display:grid;grid-template-columns:5rem minmax(0,1fr);gap:var(--space-2);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface-raised);color:var(--text);font:inherit;text-align:left;cursor:pointer}.calendar-mobile-agenda__items time,.calendar-mobile-agenda__items small,.calendar-mobile-agenda__items p{color:var(--text-muted);font-size:var(--text-size-meta)}.calendar-mobile-agenda__items span{display:grid;gap:var(--space-1)}.calendar-mobile-agenda__items p{margin:0;padding:var(--space-3);text-align:center}}
</style>
