<script setup lang="ts">
import type {ChatConversationSummaryDTO, ChatMessageDTO} from "../../../contracts/index.ts"
import AppButton from "./AppButton.vue"
import ChatMessageBubble from "./ChatMessageBubble.vue"
const props = defineProps<{selectedId: number | null; conversation: ChatConversationSummaryDTO | null; messages: ChatMessageDTO[]; hasMore: boolean; typingParticipantNames: string[]; latestOwnMessageSeen: boolean; editingId: number | null; editingDraft: string; reconnecting: boolean}>()
const emit = defineEmits<{older: []; reply: [ChatMessageDTO]; react: [ChatMessageDTO]; edit: [ChatMessageDTO]; remove: [ChatMessageDTO]; "update:editingDraft": [string]; saveEdit: [ChatMessageDTO]; cancelEdit: []; leave: []; reconnect: []}>()
const showAuthor = (message: ChatMessageDTO, index: number) => index === 0 || props.messages[index - 1]?.senderUserId !== message.senderUserId
</script>

<template>
  <main class="chat-thread" aria-live="polite"><header v-if="props.selectedId" class="chat-thread__header"><div><strong>{{ props.conversation?.title || "Conversation" }}</strong><small v-if="props.conversation?.contextType">Related to {{ props.conversation.contextType.toLowerCase() }}</small></div><AppButton v-if="props.conversation?.conversationType === 'GROUP'" type="button" tone="quiet" @click="emit('leave')">Leave group</AppButton></header><p v-if="props.reconnecting && props.selectedId" class="chat-thread__reconnect" role="status">Reconnecting to this conversation. <button type="button" @click="emit('reconnect')">Try again</button></p><AppButton v-if="props.hasMore" type="button" tone="quiet" @click="emit('older')">Load older messages</AppButton><p v-if="!props.selectedId" class="chat-thread__empty">Choose a conversation, or start a new message.</p><p v-else-if="props.messages.length === 0" class="chat-thread__empty">No messages yet. You can send the first message.</p><ChatMessageBubble v-for="(message, index) in props.messages" v-else :key="message.id" :message="message" :show-author="showAuthor(message, index)" :editing="props.editingId === message.id" :edit-draft="props.editingDraft" @reply="emit('reply', $event)" @react="emit('react', $event)" @edit="emit('edit', $event)" @remove="emit('remove', $event)" @update:edit-draft="emit('update:editingDraft', $event)" @save-edit="emit('saveEdit', $event)" @cancel-edit="emit('cancelEdit')" /><p v-if="props.typingParticipantNames.length" class="chat-thread__presence" role="status">{{ props.typingParticipantNames.join(', ') }} {{ props.typingParticipantNames.length === 1 ? 'is' : 'are' }} typing…</p><p v-else-if="props.latestOwnMessageSeen" class="chat-thread__presence">Seen</p></main>
</template>

<style scoped>
.chat-thread{display:grid;align-content:start;gap:var(--space-2);min-width:0;padding:var(--space-4);overflow:auto;background:var(--surface-base)}.chat-thread__header{display:flex;align-items:center;justify-content:space-between;gap:var(--space-2);padding-bottom:var(--space-3);border-bottom:1px solid var(--border-subtle)}.chat-thread__header div{display:grid;gap:.15rem}.chat-thread__header small,.chat-thread__empty,.chat-thread__bubble small,.chat-thread__presence{color:var(--text-muted);font-size:var(--text-size-meta)}.chat-thread__empty{margin:auto 0;padding:var(--space-5);text-align:center}.chat-thread__presence{margin:0;padding-top:var(--space-1)}.chat-thread__reconnect{margin:0;padding:var(--space-2) var(--space-3);border-radius:var(--radius-control);background:var(--surface-sunken);color:var(--text-muted);font-size:var(--text-size-meta)}.chat-thread__reconnect button{border:0;background:transparent;color:var(--accent);font:inherit;font-weight:var(--text-weight-semibold);cursor:pointer}.chat-thread__bubble{display:grid;gap:var(--space-1);max-width:min(42rem,80%);padding:var(--space-2) var(--space-3);border-radius:1rem 1rem 1rem .35rem;background:var(--surface-muted)}.chat-thread__bubble--own{justify-self:end;border-radius:1rem 1rem .35rem 1rem;background:var(--accent);color:var(--accent-contrast)}.chat-thread__bubble--own small{color:color-mix(in srgb,var(--accent-contrast) 78%,transparent)}.chat-thread__bubble p{margin:0;line-height:1.45}.chat-thread__reply{opacity:.75;font-size:var(--text-size-meta)}.chat-thread__bubble a{color:inherit;font-size:var(--text-size-meta);font-weight:var(--text-weight-semibold)}.chat-thread__actions{display:flex;gap:var(--space-1);opacity:0;transition:opacity var(--motion-fast) ease}.chat-thread__bubble:hover .chat-thread__actions,.chat-thread__bubble:focus-within .chat-thread__actions{opacity:1}.chat-thread__actions button{border:0;background:transparent;color:inherit;font:inherit;font-size:var(--text-size-meta);cursor:pointer}@media(max-width:700px){.chat-thread{padding:var(--space-3)}.chat-thread__bubble{max-width:90%}}
</style>
