<script setup lang="ts">
import {ref} from "vue"
import type {ChatMessageDTO} from "../../../contracts/index.ts"
const props = defineProps<{message: ChatMessageDTO; showAuthor: boolean; editing: boolean; editDraft: string}>()
const emit = defineEmits<{reply: [ChatMessageDTO]; react: [ChatMessageDTO]; edit: [ChatMessageDTO]; remove: [ChatMessageDTO]; "update:editDraft": [string]; saveEdit: [ChatMessageDTO]; cancelEdit: []}>()
const dateLabel = (value: string) => new Intl.DateTimeFormat(undefined, {hour: "numeric", minute: "2-digit"}).format(new Date(value))
const actionsOpen = ref(false)
let longPressTimer: number | null = null
const beginLongPress = () => { longPressTimer = window.setTimeout(() => { actionsOpen.value = true }, 450) }
const endLongPress = () => { if (longPressTimer !== null) window.clearTimeout(longPressTimer); longPressTimer = null }
</script>
<template>
  <article class="chat-message-bubble" :class="{'chat-message-bubble--own': props.message.ownMessage, 'chat-message-bubble--actions-open': actionsOpen}" @pointerdown="beginLongPress" @pointerup="endLongPress" @pointercancel="endLongPress"><small v-if="props.showAuthor">{{ props.message.senderUsername }}</small><p v-if="props.message.replyToMessageId" class="chat-message-bubble__reply">Reply to an earlier message</p><textarea v-if="props.editing" :value="props.editDraft" aria-label="Edit message" rows="2" maxlength="2000" @input="emit('update:editDraft', ($event.target as HTMLTextAreaElement).value)" /><p v-else>{{ props.message.deleted ? "Message deleted" : props.message.messageBody || props.message.attachmentName || "Attachment" }}</p><a v-if="props.message.attachmentUrl && !props.message.deleted && props.message.attachmentAvailability !== 'UNAVAILABLE'" :href="props.message.attachmentUrl || undefined" target="_blank" rel="noreferrer">Open attachment</a><small v-if="props.message.attachmentAvailability === 'UNAVAILABLE'">Attachment unavailable.</small><footer><time>{{ dateLabel(props.message.createdAt) }}</time><div v-if="props.editing" class="chat-message-bubble__actions chat-message-bubble__actions--visible"><button type="button" @click="emit('saveEdit', props.message)">Save</button><button type="button" @click="emit('cancelEdit')">Cancel</button></div><div v-else-if="!props.message.deleted" class="chat-message-bubble__actions"><button type="button" aria-label="React with thumbs up" @click="emit('react', props.message)">👍</button><button type="button" @click="emit('reply', props.message)">Reply</button><button v-if="props.message.ownMessage" type="button" @click="emit('edit', props.message)">Edit</button><button v-if="props.message.ownMessage" type="button" @click="emit('remove', props.message)">Delete</button></div></footer></article>
</template>
<style scoped>
.chat-message-bubble{display:grid;gap:var(--space-1);max-width:min(42rem,80%);padding:var(--space-2) var(--space-3);border-radius:1rem 1rem 1rem .35rem;background:var(--surface-muted)}.chat-message-bubble--own{justify-self:end;border-radius:1rem 1rem .35rem 1rem;background:var(--accent);color:var(--accent-contrast)}.chat-message-bubble small,.chat-message-bubble time{color:var(--text-muted);font-size:var(--text-size-meta)}.chat-message-bubble--own small,.chat-message-bubble--own time{color:color-mix(in srgb,var(--accent-contrast) 78%,transparent)}.chat-message-bubble p{margin:0;line-height:1.45}.chat-message-bubble textarea{width:100%;box-sizing:border-box;border:1px solid color-mix(in srgb,currentColor 35%,transparent);border-radius:var(--radius-control);padding:var(--space-2);background:color-mix(in srgb,var(--surface-base) 88%,transparent);color:var(--text);font:inherit}.chat-message-bubble__reply{opacity:.75;font-size:var(--text-size-meta)}.chat-message-bubble a{color:inherit;font-size:var(--text-size-meta);font-weight:var(--text-weight-semibold)}.chat-message-bubble footer{display:flex;align-items:center;gap:var(--space-2)}.chat-message-bubble__actions{display:flex;gap:var(--space-1);opacity:0;transition:opacity var(--motion-fast) ease}.chat-message-bubble:hover .chat-message-bubble__actions,.chat-message-bubble:focus-within .chat-message-bubble__actions,.chat-message-bubble--actions-open .chat-message-bubble__actions,.chat-message-bubble__actions--visible{opacity:1}.chat-message-bubble__actions button{border:0;background:transparent;color:inherit;font:inherit;font-size:var(--text-size-meta);cursor:pointer}@media(max-width:700px){.chat-message-bubble{max-width:90%}}
</style>
