<script setup lang="ts">
import {onBeforeUnmount, onMounted, ref} from "vue"
import {useRouter} from "vue-router"
import {userShellApi, type ActivityItem} from "../api/userShellApi.ts"

const router = useRouter()
const open = ref(false)
const items = ref<ActivityItem[]>([])
const loading = ref(false)
const error = ref("")
const load = async () => { loading.value = true; error.value = ""; try { items.value = await userShellApi.getRecentActivity() } catch { error.value = "Could not load recent work." } finally { loading.value = false } }
const openSwitcher = () => { open.value = true; void load() }
const close = () => { open.value = false }
const select = async (item: ActivityItem) => { close(); await router.push(item.route) }
const onShortcut = (event: KeyboardEvent) => { const target = event.target; const editing = target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || (target instanceof HTMLElement && target.isContentEditable); if (!editing && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "o") { event.preventDefault(); openSwitcher() } }
onMounted(() => { window.addEventListener("app:open-quick-switcher", openSwitcher); window.addEventListener("keydown", onShortcut) })
onBeforeUnmount(() => { window.removeEventListener("app:open-quick-switcher", openSwitcher); window.removeEventListener("keydown", onShortcut) })
</script>

<template>
  <div class="quick-switcher"><button type="button" class="quick-switcher__trigger" aria-label="Open recent work" title="Open recent work (Ctrl or Command O)" @click="openSwitcher">Recent</button><Teleport to="body"><div v-if="open" class="quick-switcher__backdrop" @click.self="close"><section class="quick-switcher__panel" role="dialog" aria-modal="true" aria-labelledby="quick-switcher-title" @keydown.esc="close"><header><div><p>Quick switcher</p><h2 id="quick-switcher-title">Recent work</h2></div><button type="button" aria-label="Close recent work" @click="close">×</button></header><p v-if="loading" class="quick-switcher__state" role="status">Loading recent work…</p><p v-else-if="error" class="quick-switcher__state quick-switcher__state--error" role="alert">{{ error }}</p><p v-else-if="!items.length" class="quick-switcher__state">No recent work is available yet.</p><button v-for="item in items" v-else :key="`${item.kind}-${item.resumeKey || item.route}`" type="button" class="quick-switcher__item" @click="select(item)"><span>{{ item.kind }}</span><strong>{{ item.title }}</strong><small>{{ item.summary }}</small></button></section></div></Teleport></div>
</template>

<style scoped>
.quick-switcher__trigger { min-height: var(--control-height-default); padding: var(--space-1) var(--space-2); border: 1px solid var(--control-border); border-radius: var(--radius-control); background: var(--control-bg); color: var(--control-ink-muted); font: inherit; font-size: var(--text-size-body); font-weight: var(--text-weight-semibold); cursor: pointer; }.quick-switcher__trigger:hover, .quick-switcher__trigger:focus-visible { border-color: var(--control-border-active); background: var(--control-bg-hover); color: var(--control-ink); }.quick-switcher__trigger:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }.quick-switcher__backdrop { position: fixed; inset: 0; z-index: var(--z-dialog); display: grid; place-items: start center; padding: 12vh var(--space-3) var(--space-3); background: rgba(0,0,0,.64); }.quick-switcher__panel { width: min(100%, 36rem); display: grid; gap: var(--space-1); border: 1px solid var(--border-strong); border-radius: var(--radius-surface); background: var(--surface-raised); box-shadow: var(--shadow-overlay); overflow: hidden; }.quick-switcher__panel header { display: flex; align-items: center; justify-content: space-between; padding: var(--space-3); border-bottom: 1px solid var(--border-subtle); }.quick-switcher__panel header p, .quick-switcher__panel h2 { margin: 0; }.quick-switcher__panel header p, .quick-switcher__item span { color: var(--text-soft); font-size: var(--text-size-label); text-transform: uppercase; letter-spacing: var(--tracking-label); }.quick-switcher__panel h2 { font-size: var(--text-size-title); }.quick-switcher__panel header button { width: var(--control-height-default); height: var(--control-height-default); border: 1px solid transparent; border-radius: var(--radius-control); background: transparent; color: var(--text-muted); font-size: 1.25rem; cursor: pointer; }.quick-switcher__panel header button:hover, .quick-switcher__panel header button:focus-visible { border-color: var(--control-border); background: var(--surface-hover); color: var(--text); }.quick-switcher__panel header button:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }.quick-switcher__state { margin: var(--space-3); color: var(--text-muted); font-size: var(--text-size-body); }.quick-switcher__state--error { color: var(--danger); }.quick-switcher__item { display: grid; gap: var(--space-1); padding: var(--space-2) var(--space-3); border: 0; background: transparent; color: var(--text); text-align: left; cursor: pointer; }.quick-switcher__item:hover, .quick-switcher__item:focus-visible { background: var(--surface-hover); }.quick-switcher__item:focus-visible { outline: var(--focus-ring); outline-offset: -2px; }.quick-switcher__item small { color: var(--text-muted); font-size: var(--text-size-meta); }
</style>
