<script setup lang="ts">
import {RouterLink} from "vue-router"
import type {DisplayDensity} from "../api/userShellApi.ts"
import type {ShellSurfaceRow} from "../shellSurfaceData.ts"

withDefaults(defineProps<{row: Omit<ShellSurfaceRow, "id"> & {id?: string}; selected?: boolean; density?: DisplayDensity}>(), {density: "default"})
</script>

<template>
  <article class="surface-row" :data-collection-row-id="row.id" data-trust-cue="viewer-scoped-row" data-mobile-context="open-detail" :class="[`surface-row--${density}`, {'surface-row--selected': selected, 'surface-row--informational': !row.to}]">
    <RouterLink v-if="row.to" :to="row.to" class="surface-row__primary" :aria-label="`Open ${row.title}`"><img v-if="row.thumbnailUrl" class="surface-row__thumbnail" :src="row.thumbnailUrl" alt=""><div class="surface-row__main"><div class="surface-row__title-line"><strong>{{ row.title }}</strong><span v-if="row.badge" class="surface-row__badge">{{ row.badge }}</span></div><span class="surface-row__description">{{ row.description }}</span></div><span v-if="row.meta" class="surface-row__meta">{{ row.meta }}</span></RouterLink>
    <template v-else><div class="surface-row__main"><div class="surface-row__title-line"><strong>{{ row.title }}</strong><span v-if="row.badge" class="surface-row__badge">{{ row.badge }}</span></div><span class="surface-row__description">{{ row.description }}</span></div><span v-if="row.meta" class="surface-row__meta">{{ row.meta }}</span></template>
    <div v-if="$slots.actions" class="surface-row__actions"><slot name="actions" /></div>
  </article>
</template>

<style scoped>
.surface-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:var(--space-2);width:100%;min-height:var(--dense-row-height-default);border-bottom:1px solid var(--border-subtle)}.surface-row--compact,.surface-row--compact .surface-row__primary{min-height:var(--dense-row-height-compact)}.surface-row--comfortable,.surface-row--comfortable .surface-row__primary{min-height:var(--dense-row-height-comfortable)}.surface-row--selected{background:var(--native-selection);box-shadow:inset 2px 0 var(--accent)}.surface-row__primary{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:var(--space-2);min-width:0;min-height:var(--dense-row-height-default);padding:var(--space-2) var(--space-3);border-radius:var(--radius-control)}.surface-row__primary:hover{background:var(--surface-hover)}.surface-row__primary:focus-visible{outline:var(--focus-ring);outline-offset:-2px}.surface-row__main{display:grid;gap:var(--space-1);min-width:0;padding:var(--space-2) var(--space-3)}.surface-row__primary .surface-row__main{padding:0}.surface-row__title-line{display:flex;align-items:center;gap:var(--space-2);min-width:0}.surface-row__title-line strong,.surface-row__description{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.surface-row__title-line strong{color:var(--text);font-size:var(--text-size-title);font-weight:var(--text-weight-semibold)}.surface-row__description{color:var(--text-muted);font-size:var(--text-size-body)}.surface-row__meta{padding-right:var(--space-3);color:var(--text-soft);font-size:var(--text-size-meta);text-align:right}.surface-row__badge{padding:0 var(--space-1);border:1px solid var(--border-subtle);border-radius:var(--radius-control);color:var(--text-muted);font-size:var(--text-size-label)}.surface-row__thumbnail{width:3rem;height:3rem;object-fit:cover;border-radius:var(--radius-control)}.surface-row__actions{display:flex;gap:var(--space-1);padding-right:var(--space-3)}@media(max-width:700px){.surface-row{grid-template-columns:1fr}.surface-row__primary{grid-template-columns:1fr}.surface-row__meta{padding:0 var(--space-3) var(--space-2);text-align:left}.surface-row__actions{padding:0 var(--space-3) var(--space-2);flex-wrap:wrap}}
</style>
