name: Dora control

on:
  pull_request:
  push:

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dora doctor
        run: "{{doctor}}"
      - name: Validate Dora adapter
        run: "{{adapter_validation}}"
      - name: Project setup
        run: "{{setup}}"
      - name: Project tests
        run: "{{test}}"
      - name: Project build
        run: "{{build}}"
